### ISSUE TITLE
Reaction origin is not reported when visualizing an annotated chemkin file

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-website#101]
It simply print `reaction:` in each reaction line. It also does not list the reaction families in the section above the individual reactions.

![image](https://cloud.githubusercontent.com/assets/242147/11661279/1d585bb0-9d9f-11e5-979b-ac128c184877.png)

**Comment by KEHANG** [comment]
@nickvandewiele can you show some parts of the chem.inp file you are trying to visualize? is it a merged mechanism?

**Comment by nickvandewiele** [comment]
`minimal` example of RMG-Py produced by v1.0.0.
[chem_annotated.txt](https://github.com/ReactionMechanismGenerator/RMG-website/files/78960/chem_annotated.txt)
[species_dictionary.txt](https://github.com/ReactionMechanismGenerator/RMG-website/files/78961/species_dictionary.txt)

**Comment by KEHANG** [comment]
@nickvandewiele OK, I think pull request [#511](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/511) will solve this issue.
