### ISSUE TITLE
Input file generator doesn't render images of species

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-website#106]
When I enter butane, for example, it tries to show this image ![butane](http://rmg.mit.edu/molecule/1%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B5,S%7D%20%7B6,S%7D%20%7B7,S%7D;2%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B3,S%7D%20%7B8,S%7D%20%7B9,S%7D;3%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B4,S%7D%20%7B10,S%7D%20%7B11,S%7D;4%20C%20u0%20p0%20c0%20%7B3,S%7D%20%7B12,S%7D%20%7B13,S%7D%20%7B14,S%7D;5%20H%20u0%20p0%20c0%20%7B1,S%7D;6%20H%20u0%20p0%20c0%20%7B1,S%7D;7%20H%20u0%20p0%20c0%20%7B1,S%7D;8%20H%20u0%20p0%20c0%20%7B2,S%7D;9%20H%20u0%20p0%20c0%20%7B2,S%7D;10%20H%20u0%20p0%20c0%20%7B3,S%7D;11%20H%20u0%20p0%20c0%20%7B3,S%7D;12%20H%20u0%20p0%20c0%20%7B4,S%7D;13%20H%20u0%20p0%20c0%20%7B4,S%7D;14%20H%20u0%20p0%20c0%20%7B4,S%7D;)

`http://rmg.mit.edu/molecule/1%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B5,S%7D%20%7B6,S%7D%20%7B7,S%7D;2%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B3,S%7D%20%7B8,S%7D%20%7B9,S%7D;3%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B4,S%7D%20%7B10,S%7D%20%7B11,S%7D;4%20C%20u0%20p0%20c0%20%7B3,S%7D%20%7B12,S%7D%20%7B13,S%7D%20%7B14,S%7D;5%20H%20u0%20p0%20c0%20%7B1,S%7D;6%20H%20u0%20p0%20c0%20%7B1,S%7D;7%20H%20u0%20p0%20c0%20%7B1,S%7D;8%20H%20u0%20p0%20c0%20%7B2,S%7D;9%20H%20u0%20p0%20c0%20%7B2,S%7D;10%20H%20u0%20p0%20c0%20%7B3,S%7D;11%20H%20u0%20p0%20c0%20%7B3,S%7D;12%20H%20u0%20p0%20c0%20%7B4,S%7D;13%20H%20u0%20p0%20c0%20%7B4,S%7D;14%20H%20u0%20p0%20c0%20%7B4,S%7D;`

This gives an error `invalid literal for int() with base 10: ''`

**Comment by connie** [comment]
In general the Input File Form does not save files properly, nor load them properly whenever new parameters are added to the input file.  And now django's sql table migrations are a much bigger pain to do because we upgraded to 1.8.4.  I do think a lot of people want to use the web form because it's a lot more human readable, so maybe a urop or first should should take over the django maintenance?

**Comment by mliu49** [comment]
This is a result of the switch to urllib for converting adjlists (c4130530d37aecda668c6ef5ca2ea61583d5276e). I can push a fix.

**Comment by connie** [comment]
Does this mean all of our old URLS will no longer work? As in, old HTML visualized files with links?  Not a huge concern, just wondering.

**Comment by rwest** [comment]
Yes Connie. See comments at https://github.com/ReactionMechanismGenerator/RMG-Py/issues/668
