### ISSUE TITLE
NCI resolver about to turn of HTTP access (switching to HTTPS)

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-website#107]
Just noticed this at http://cactus.nci.nih.gov

> Notice: The CACTUS web server has been migrated to a significantly reconfigured system on new hardware (with a new IPv4 address). The HTTPS protocol has been enabled for all services. Both HTTP and HTTPS will be supported in parallel for a transition period. We plan to turn off HTTP permanently by end of March 2016. If you encounter any bugs or behavior different from the old server, please let us know immediately.

Notice the March 2016 deadline

**Comment by mliu49** [comment]
We switched to using the HTTPS link in #143.
