### ISSUE TITLE
'rmgpy.molecule.molecule.Molecule' object has no attribute 'molecule' when looking for reactions.

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-website#111]
The inflate/deflate etc. changes of https://github.com/ReactionMechanismGenerator/RMG-Py/commit/c147f77a056531d7c135b66b267ae1e29d0b0919
changed the rmgpy.data.kinetics.family.generateReactions method so that it now returns reactions containing Molecule objects not Species objects.

That causes the following problem in the RMG-website:
 
[http://127.0.0.1:8000/database/kinetics/reaction/reactant1...etc....](http://127.0.0.1:8000/database/kinetics/reaction/reactant1%3Dmultiplicity%25203%250A1%2520%2520C%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%2520%257B3%252CS%257D%2520%257B5%252CS%257D%2520%257B6%252CS%257D%250A2%2520%2520C%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%2520%257B4%252CS%257D%2520%257B7%252CS%257D%2520%257B8%252CS%257D%250A3%2520%2520C%2520u1%2520p0%2520c0%2520%257B1%252CS%257D%2520%257B9%252CS%257D%2520%257B10%252CS%257D%250A4%2520%2520C%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%2520%257B11%252CD%257D%2520%257B12%252CS%257D%250A5%2520%2520H%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%250A6%2520%2520H%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%250A7%2520%2520H%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%250A8%2520%2520H%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%250A9%2520%2520O%2520u1%2520p2%2520c0%2520%257B3%252CS%257D%250A10%2520H%2520u0%2520p0%2520c0%2520%257B3%252CS%257D%250A11%2520O%2520u0%2520p2%2520c0%2520%257B4%252CD%257D%250A12%2520H%2520u0%2520p0%2520c0%2520%257B4%252CS%257D%250A__reactant2%3D1%2520%2520C%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%2520%257B5%252CS%257D%2520%257B11%252CS%257D%2520%257B12%252CS%257D%250A2%2520%2520C%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%2520%257B3%252CS%257D%2520%257B13%252CS%257D%2520%257B14%252CS%257D%250A3%2520%2520C%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%2520%257B4%252CS%257D%2520%257B15%252CS%257D%2520%257B16%252CS%257D%250A4%2520%2520C%2520u0%2520p0%2520c0%2520%257B3%252CS%257D%2520%257B6%252CS%257D%2520%257B17%252CS%257D%2520%257B18%252CS%257D%250A5%2520%2520C%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%2520%257B7%252CS%257D%2520%257B9%252CS%257D%2520%257B10%252CS%257D%250A6%2520%2520C%2520u0%2520p0%2520c0%2520%257B4%252CS%257D%2520%257B8%252CS%257D%2520%257B19%252CS%257D%2520%257B20%252CS%257D%250A7%2520%2520C%2520u0%2520p0%2520c0%2520%257B5%252CS%257D%2520%257B21%252CS%257D%2520%257B22%252CS%257D%2520%257B23%252CS%257D%250A8%2520%2520C%2520u0%2520p0%2520c0%2520%257B6%252CS%257D%2520%257B24%252CS%257D%2520%257B25%252CS%257D%2520%257B26%252CS%257D%250A9%2520%2520H%2520u0%2520p0%2520c0%2520%257B5%252CS%257D%250A10%2520H%2520u0%2520p0%2520c0%2520%257B5%252CS%257D%250A11%2520H%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%250A12%2520H%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%250A13%2520H%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%250A14%2520H%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%250A15%2520H%2520u0%2520p0%2520c0%2520%257B3%252CS%257D%250A16%2520H%2520u0%2520p0%2520c0%2520%257B3%252CS%257D%250A17%2520H%2520u0%2520p0%2520c0%2520%257B4%252CS%257D%250A18%2520H%2520u0%2520p0%2520c0%2520%257B4%252CS%257D%250A19%2520H%2520u0%2520p0%2520c0%2520%257B6%252CS%257D%250A20%2520H%2520u0%2520p0%2520c0%2520%257B6%252CS%257D%250A21%2520H%2520u0%2520p0%2520c0%2520%257B7%252CS%257D%250A22%2520H%2520u0%2520p0%2520c0%2520%257B7%252CS%257D%250A23%2520H%2520u0%2520p0%2520c0%2520%257B7%252CS%257D%250A24%2520H%2520u0%2520p0%2520c0%2520%257B8%252CS%257D%250A25%2520H%2520u0%2520p0%2520c0%2520%257B8%252CS%257D%250A26%2520H%2520u0%2520p0%2520c0%2520%257B8%252CS%257D%250A__product1%3Dmultiplicity%25202%250A1%2520%2520C%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%2520%257B3%252CS%257D%2520%257B5%252CS%257D%2520%257B6%252CS%257D%250A2%2520%2520C%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%2520%257B4%252CS%257D%2520%257B7%252CS%257D%2520%257B8%252CS%257D%250A3%2520%2520C%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%2520%257B9%252CS%257D%2520%257B10%252CS%257D%2520%257B11%252CS%257D%250A4%2520%2520C%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%2520%257B12%252CD%257D%2520%257B13%252CS%257D%250A5%2520%2520H%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%250A6%2520%2520H%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%250A7%2520%2520H%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%250A8%2520%2520H%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%250A9%2520%2520O%2520u1%2520p2%2520c0%2520%257B3%252CS%257D%250A10%2520H%2520u0%2520p0%2520c0%2520%257B3%252CS%257D%250A11%2520H%2520u0%2520p0%2520c0%2520%257B3%252CS%257D%250A12%2520O%2520u0%2520p2%2520c0%2520%257B4%252CD%257D%250A13%2520H%2520u0%2520p0%2520c0%2520%257B4%252CS%257D%250A__product2%3Dmultiplicity%25202%250A1%2520%2520C%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%2520%257B5%252CS%257D%2520%257B11%252CS%257D%2520%257B12%252CS%257D%250A2%2520%2520C%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%2520%257B3%252CS%257D%2520%257B13%252CS%257D%2520%257B14%252CS%257D%250A3%2520%2520C%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%2520%257B4%252CS%257D%2520%257B15%252CS%257D%2520%257B16%252CS%257D%250A4%2520%2520C%2520u0%2520p0%2520c0%2520%257B3%252CS%257D%2520%257B6%252CS%257D%2520%257B17%252CS%257D%2520%257B18%252CS%257D%250A5%2520%2520C%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%2520%257B7%252CS%257D%2520%257B9%252CS%257D%2520%257B10%252CS%257D%250A6%2520%2520C%2520u0%2520p0%2520c0%2520%257B4%252CS%257D%2520%257B8%252CS%257D%2520%257B19%252CS%257D%2520%257B20%252CS%257D%250A7%2520%2520C%2520u0%2520p0%2520c0%2520%257B5%252CS%257D%2520%257B21%252CS%257D%2520%257B22%252CS%257D%2520%257B23%252CS%257D%250A8%2520%2520C%2520u1%2520p0%2520c0%2520%257B6%252CS%257D%2520%257B24%252CS%257D%2520%257B25%252CS%257D%250A9%2520%2520H%2520u0%2520p0%2520c0%2520%257B5%252CS%257D%250A10%2520H%2520u0%2520p0%2520c0%2520%257B5%252CS%257D%250A11%2520H%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%250A12%2520H%2520u0%2520p0%2520c0%2520%257B1%252CS%257D%250A13%2520H%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%250A14%2520H%2520u0%2520p0%2520c0%2520%257B2%252CS%257D%250A15%2520H%2520u0%2520p0%2520c0%2520%257B3%252CS%257D%250A16%2520H%2520u0%2520p0%2520c0%2520%257B3%252CS%257D%250A17%2520H%2520u0%2520p0%2520c0%2520%257B4%252CS%257D%250A18%2520H%2520u0%2520p0%2520c0%2520%257B4%252CS%257D%250A19%2520H%2520u0%2520p0%2520c0%2520%257B6%252CS%257D%250A20%2520H%2520u0%2520p0%2520c0%2520%257B6%252CS%257D%250A21%2520H%2520u0%2520p0%2520c0%2520%257B7%252CS%257D%250A22%2520H%2520u0%2520p0%2520c0%2520%257B7%252CS%257D%250A23%2520H%2520u0%2520p0%2520c0%2520%257B7%252CS%257D%250A24%2520H%2520u0%2520p0%2520c0%2520%257B8%252CS%257D%250A25%2520H%2520u0%2520p0%2520c0%2520%257B8%252CS%257D%250A)
```
Django Version: 1.9.5
Python Version: 2.7.11
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.admin',
 'rmgweb.main',
 'rmgweb.main.templatetags',
 'rmgweb.database',
 'rmgweb.pdep',
 'rmgweb.rmg')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')



Traceback:

File "/Users/rwest/anaconda/envs/rmg5/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/Users/rwest/anaconda/envs/rmg5/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/rwest/Code/RMG-website/rmgweb/database/views.py" in kineticsData
  2203.             generateSpeciesThermo(reactant, database)

File "/Users/rwest/Code/RMG-website/rmgweb/database/tools.py" in generateSpeciesThermo
  333.     species.thermo = database.thermo.getThermoData(species)

File "/Users/rwest/Code/RMG-Py/rmgpy/data/thermo.py" in getThermoData
  726.         thermo0 = self.getThermoDataFromLibraries(species)

File "/Users/rwest/Code/RMG-Py/rmgpy/data/thermo.py" in getThermoDataFromLibraries
  879.             thermoData = self.getThermoDataFromLibrary(species, self.libraries[label])

File "/Users/rwest/Code/RMG-Py/rmgpy/data/thermo.py" in getThermoDataFromLibrary
  968.             for molecule in species.molecule:

Exception Type: AttributeError at /database/kinetics/reaction/reactant1=multiplicity%203%0A1%20%20C%20u0%20p0%20c0%20%7B2%2CS%7D%20%7B3%2CS%7D%20%7B5%2CS%7D%20%7B6%2CS%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1%2CS%7D%20%7B4%2CS%7D%20%7B7%2CS%7D%20%7B8%2CS%7D%0A3%20%20C%20u1%20p0%20c0%20%7B1%2CS%7D%20%7B9%2CS%7D%20%7B10%2CS%7D%0A4%20%20C%20u0%20p0%20c0%20%7B2%2CS%7D%20%7B11%2CD%7D%20%7B12%2CS%7D%0A5%20%20H%20u0%20p0%20c0%20%7B1%2CS%7D%0A6%20%20H%20u0%20p0%20c0%20%7B1%2CS%7D%0A7%20%20H%20u0%20p0%20c0%20%7B2%2CS%7D%0A8%20%20H%20u0%20p0%20c0%20%7B2%2CS%7D%0A9%20%20O%20u1%20p2%20c0%20%7B3%2CS%7D%0A10%20H%20u0%20p0%20c0%20%7B3%2CS%7D%0A11%20O%20u0%20p2%20c0%20%7B4%2CD%7D%0A12%20H%20u0%20p0%20c0%20%7B4%2CS%7D%0A__reactant2=1%20%20C%20u0%20p0%20c0%20%7B2%2CS%7D%20%7B5%2CS%7D%20%7B11%2CS%7D%20%7B12%2CS%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1%2CS%7D%20%7B3%2CS%7D%20%7B13%2CS%7D%20%7B14%2CS%7D%0A3%20%20C%20u0%20p0%20c0%20%7B2%2CS%7D%20%7B4%2CS%7D%20%7B15%2CS%7D%20%7B16%2CS%7D%0A4%20%20C%20u0%20p0%20c0%20%7B3%2CS%7D%20%7B6%2CS%7D%20%7B17%2CS%7D%20%7B18%2CS%7D%0A5%20%20C%20u0%20p0%20c0%20%7B1%2CS%7D%20%7B7%2CS%7D%20%7B9%2CS%7D%20%7B10%2CS%7D%0A6%20%20C%20u0%20p0%20c0%20%7B4%2CS%7D%20%7B8%2CS%7D%20%7B19%2CS%7D%20%7B20%2CS%7D%0A7%20%20C%20u0%20p0%20c0%20%7B5%2CS%7D%20%7B21%2CS%7D%20%7B22%2CS%7D%20%7B23%2CS%7D%0A8%20%20C%20u0%20p0%20c0%20%7B6%2CS%7D%20%7B24%2CS%7D%20%7B25%2CS%7D%20%7B26%2CS%7D%0A9%20%20H%20u0%20p0%20c0%20%7B5%2CS%7D%0A10%20H%20u0%20p0%20c0%20%7B5%2CS%7D%0A11%20H%20u0%20p0%20c0%20%7B1%2CS%7D%0A12%20H%20u0%20p0%20c0%20%7B1%2CS%7D%0A13%20H%20u0%20p0%20c0%20%7B2%2CS%7D%0A14%20H%20u0%20p0%20c0%20%7B2%2CS%7D%0A15%20H%20u0%20p0%20c0%20%7B3%2CS%7D%0A16%20H%20u0%20p0%20c0%20%7B3%2CS%7D%0A17%20H%20u0%20p0%20c0%20%7B4%2CS%7D%0A18%20H%20u0%20p0%20c0%20%7B4%2CS%7D%0A19%20H%20u0%20p0%20c0%20%7B6%2CS%7D%0A20%20H%20u0%20p0%20c0%20%7B6%2CS%7D%0A21%20H%20u0%20p0%20c0%20%7B7%2CS%7D%0A22%20H%20u0%20p0%20c0%20%7B7%2CS%7D%0A23%20H%20u0%20p0%20c0%20%7B7%2CS%7D%0A24%20H%20u0%20p0%20c0%20%7B8%2CS%7D%0A25%20H%20u0%20p0%20c0%20%7B8%2CS%7D%0A26%20H%20u0%20p0%20c0%20%7B8%2CS%7D%0A__product1=multiplicity%202%0A1%20%20C%20u0%20p0%20c0%20%7B2%2CS%7D%20%7B3%2CS%7D%20%7B5%2CS%7D%20%7B6%2CS%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1%2CS%7D%20%7B4%2CS%7D%20%7B7%2CS%7D%20%7B8%2CS%7D%0A3%20%20C%20u0%20p0%20c0%20%7B1%2CS%7D%20%7B9%2CS%7D%20%7B10%2CS%7D%20%7B11%2CS%7D%0A4%20%20C%20u0%20p0%20c0%20%7B2%2CS%7D%20%7B12%2CD%7D%20%7B13%2CS%7D%0A5%20%20H%20u0%20p0%20c0%20%7B1%2CS%7D%0A6%20%20H%20u0%20p0%20c0%20%7B1%2CS%7D%0A7%20%20H%20u0%20p0%20c0%20%7B2%2CS%7D%0A8%20%20H%20u0%20p0%20c0%20%7B2%2CS%7D%0A9%20%20O%20u1%20p2%20c0%20%7B3%2CS%7D%0A10%20H%20u0%20p0%20c0%20%7B3%2CS%7D%0A11%20H%20u0%20p0%20c0%20%7B3%2CS%7D%0A12%20O%20u0%20p2%20c0%20%7B4%2CD%7D%0A13%20H%20u0%20p0%20c0%20%7B4%2CS%7D%0A__product2=multiplicity%202%0A1%20%20C%20u0%20p0%20c0%20%7B2%2CS%7D%20%7B5%2CS%7D%20%7B11%2CS%7D%20%7B12%2CS%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1%2CS%7D%20%7B3%2CS%7D%20%7B13%2CS%7D%20%7B14%2CS%7D%0A3%20%20C%20u0%20p0%20c0%20%7B2%2CS%7D%20%7B4%2CS%7D%20%7B15%2CS%7D%20%7B16%2CS%7D%0A4%20%20C%20u0%20p0%20c0%20%7B3%2CS%7D%20%7B6%2CS%7D%20%7B17%2CS%7D%20%7B18%2CS%7D%0A5%20%20C%20u0%20p0%20c0%20%7B1%2CS%7D%20%7B7%2CS%7D%20%7B9%2CS%7D%20%7B10%2CS%7D%0A6%20%20C%20u0%20p0%20c0%20%7B4%2CS%7D%20%7B8%2CS%7D%20%7B19%2CS%7D%20%7B20%2CS%7D%0A7%20%20C%20u0%20p0%20c0%20%7B5%2CS%7D%20%7B21%2CS%7D%20%7B22%2CS%7D%20%7B23%2CS%7D%0A8%20%20C%20u1%20p0%20c0%20%7B6%2CS%7D%20%7B24%2CS%7D%20%7B25%2CS%7D%0A9%20%20H%20u0%20p0%20c0%20%7B5%2CS%7D%0A10%20H%20u0%20p0%20c0%20%7B5%2CS%7D%0A11%20H%20u0%20p0%20c0%20%7B1%2CS%7D%0A12%20H%20u0%20p0%20c0%20%7B1%2CS%7D%0A13%20H%20u0%20p0%20c0%20%7B2%2CS%7D%0A14%20H%20u0%20p0%20c0%20%7B2%2CS%7D%0A15%20H%20u0%20p0%20c0%20%7B3%2CS%7D%0A16%20H%20u0%20p0%20c0%20%7B3%2CS%7D%0A17%20H%20u0%20p0%20c0%20%7B4%2CS%7D%0A18%20H%20u0%20p0%20c0%20%7B4%2CS%7D%0A19%20H%20u0%20p0%20c0%20%7B6%2CS%7D%0A20%20H%20u0%20p0%20c0%20%7B6%2CS%7D%0A21%20H%20u0%20p0%20c0%20%7B7%2CS%7D%0A22%20H%20u0%20p0%20c0%20%7B7%2CS%7D%0A23%20H%20u0%20p0%20c0%20%7B7%2CS%7D%0A24%20H%20u0%20p0%20c0%20%7B8%2CS%7D%0A25%20H%20u0%20p0%20c0%20%7B8%2CS%7D%0A
Exception Value: 'rmgpy.molecule.molecule.Molecule' object has no attribute 'molecule'

```

**Comment by nickvandewiele** [comment]
You are correct, changes due to the [KineticsFamily.generateReactions](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/data/kinetics/family.py#L1295) in light of the parallelization of the reaction generations did break this.

That method returns `Reaction` objects with `Molecule` objects as reactants/products, rather than `Species` objects in the past.

However, I think it's equally important to think about the reason that I did not catch this bug earlier:
- we have no unit tests that test stuff from the website
- the `rmgweb.database.views` module is clearly doing much more than building views! It is calculating a lot of _chemistry_, which should ideally be computed in RMG-Py and accessed through an API. The shear number of `from rmgpy.* import *` is a silent witness that, whatever we change in RMG-Py will always require us to look to RMG-Website as well.

@connie @mliu49

**Comment by nickvandewiele** [comment]
For this specific bug, I'd suggest to move [rmgweb.database.tools.generateReactions](https://github.com/ReactionMechanismGenerator/RMG-website/blob/master/rmgweb/database/tools.py#L337) back to RMG-Py, and fixing it so that Molecule objects are converted into Species objects.

As far as I can see, this function has no dependencies to RMG-Website, whatsoever.

**Comment by connie** [comment]
I agree with you.  It is definitely redundant to have in rmgweb.  We should probably try keeping most methods in RMG-Py and do only formatting to HTML stuff in rmgweb.
