### ISSUE TITLE
URL length causing problems

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-website#113]
I think this issue became more prevalent after the switch to urllib because the urls became slightly longer. This mostly applies to kinetics searches, and was also encountered in ReactionMechanismGenerator/RMG-Py#674. After getting to the results page, clicking on the results for a particular reaction will sometimes lead to an error saying

    Not Found
    The requested URL
    /database/kinetics/reaction/reactant1=...
    was not found on this server.

This appears to be solely dependent on URL length. After some trial and error, I found that at some point between a total url length of 6063 and 6075 characters, this error appears. This can be observed directly by searching for reactions between `C1CCCCC1CO` and `C1=CC=CC=C1C`. The reactions giving two products will give the error, while the reactions producing a single product will work fine.

At some point around 8000 characters, the error message changes to

    Request-URI Too Long
    The requested URL's length exceeds the capacity limit for this server.

I'm not sure exactly what causes the Not Found error before actually hitting the URL length limit. As a side note, I wasn't able to reproduce either message on my local website, which supports it being a server issue.

Two options I can think of for addressing this are

1. Looking into changing server settings or something to remove this limitation.
2. Not encoding adjlists into the URL - maybe switch to augmented InChI?

**Comment by rwest** [comment]
Having explicit hydrogens in all the adjacency lists also lengthens the URLs. It would be nice if we could make adjlists without them. Augmented InChI is a nice idea too, if it's reliable enough (adjlist -> auginchi ->adjlist *always* returns the same thing?), but wouldn't work for URLs that need to encode the labeled atoms (if such URLs ever exist?).

**Comment by mliu49** [comment]
This should be greatly mitigated by fixing the double-encoding issue. Since that fix reduced the length of urls (by approximately half), we can now handle longer urls before meeting this limit. However, the root issue of not being able to handle extra long urls seems to be a limitation (possibly a setting) of apache.
