### ISSUE TITLE
Unit testing for RMG-website

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-website#114]
Nick previously brought up the fact that the effects which RMG-Py changes have on the website are not readily apparent due to the lack of a test suite for the website.

To address that and to aid future website development, I want to start developing some unit tests. I started this issue to get ideas for unit tests to create and their prioritization. Any thoughts or suggestions would be greatly appreciated!

**Comment by nickvandewiele** [comment]
Django has an entire section dedicated to emulating user interaction:
https://docs.djangoproject.com/en/1.9/topics/testing/overview/
