### ISSUE TITLE
Link to reaction family list doesn't go to correct place

### ISSUE THREAD

**Issue by bslakman** [ReactionMechanismGenerator/RMG-website#122]
At the bottom of [this page](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/kinetics.html#kinetics) there is a link to "Full List of the Kinetics Families". When you click the link, it goes [here](http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/input.html#kineticsfamilies) instead, which is the description of how to add kinetics families to your input file.

**Comment by mliu49** [comment]
This has been fixed.
