### ISSUE TITLE
Segmentation fault 11 OSX 10.11.6

### ISSUE THREAD

**Issue by tobikone** [ReactionMechanismGenerator/RMG-website#125]
I installed the RMG python version along with Anaconda. There were no errors during the installation and I am able to call the rmg_env. Whenever I try to run the Minimal input file to verify the installation. I got "segmentation fault: 11".

I downloaded the anaconda python platform and installed it. Then use that to install the rmg and its database.

I did this in my Macbook, OSX 10.11.6 El Capitan.  I suspect the issue is related to the OSX.

**Comment by nyee** [comment]
We most often see this error if the program is not properly compiled. Trying running these two commands when in the RMG-Py directory:
```
make clean
make
```

It should take about 10 minutes or so compile. Then try the minimal example again.

**Comment by tobikone** [comment]
Thanks, I tried that and it did not install. Also, I did not installed it by source. Instead I used the Binary Installation. It took me less than two minutes to compile it. I tried installing it by source and I ran to the same issue.
Again, thank you for your assistance.

Best,

**Comment by nyee** [comment]
Sorry, I'm a little confused. Is it working now or not?

**Comment by mliu49** [comment]
Hi, could you answer some questions to help us figure out the problem?

Were you following these instructions for the installation?
http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaUser.html

Could you check your Python version (from within the environment)?
```
python --version
```

**Comment by tobikone** [comment]
Sorry, it is not working. I was just expressing to show my gratitude for your help. I tried rebuilding the anaconda and RMG. The compilation did take several minutes and it successfully completed. I still, however, encountered the Segmentation Fault 11 issue.
I am following the instruction from this link:  http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaUser.html

**Comment by tobikone** [comment]
My python version within the environment is 2.7.12

**Comment by KEHANG** [comment]
can you run:
```
source activate rmg_env
conda list
```
and send us a screenshot?

**Comment by tobikone** [comment]
Here is the list I got:

![screen shot 2016-10-18 at 5 56 47 pm](https://cloud.githubusercontent.com/assets/13335862/19497882/5d59953e-955c-11e6-8261-19482c7d067e.png)
![screen shot 2016-10-18 at 5 57 01 pm](https://cloud.githubusercontent.com/assets/13335862/19497883/5d633792-955c-11e6-8871-3a6e23a1eb6f.png)
![screen shot 2016-10-18 at 5 57 11 pm](https://cloud.githubusercontent.com/assets/13335862/19497884/5d69a136-955c-11e6-8bd7-6311a8a923b4.png)

**Comment by KEHANG** [comment]
that seems fine to me, can you run the minimal example :
```
python /path/to/your/RMG-Py repo/rmg.py input.py
```
show us the detailed traceback of the error?

**Comment by tobikone** [comment]
This is all the error I am getting.

![screen shot 2016-10-18 at 6 09 31 pm](https://cloud.githubusercontent.com/assets/13335862/19498291/0fc0f798-955e-11e6-8e99-a984e7309ebd.png)

**Comment by mliu49** [comment]
This does seem like an OSX issue.

Can you try starting the python shell in terminal and test these commands? Just type `python` to start the shell while in the environment.
```
import rmgpy
import pydas
import pydqed
import numpy
import cython
import rdkit
import cairo
import pydot
```
I expect them to give the same error. Tell us if any of them work without a segmentation fault.

**Comment by tobikone** [comment]
I tried those lines in python while in the rmg env and I got the following:
![screen shot 2016-10-18 at 8 13 07 pm](https://cloud.githubusercontent.com/assets/13335862/19500907/606aca28-956f-11e6-940a-6dd5873c7ba2.png)

It seems the issue lies with the rdkit. I did installed rdkit in my OS a while ago. Could it be conflicting w the old installation?

**Comment by KEHANG** [comment]
two checks might help identify the root problem:
- exit `rmg_env` and enter **native** python shell, try to `import rdkit` (it should try to import the old rdkit) there and see if you get the same `Segmentation fault`. 
- take a look at your `.bash_profile` file to see if old `rdkit` installation path is still included in the `PATH` and `PYTHONPATH`. Try to print out them.

**Comment by tobikone** [comment]
Kehang,

Indeed, I got the same error for rdkit when I'm outside of the environment. The only path to RDKIT I have in my .bashrc is the following:

PATH=$PATH:/home/username/bin:/usr/local/homebrew

export path

export RDBASE=/usr/local/share/RDKit
export RMG=/Users/taufikridha/RMG-Java

I think removed the path to RDKIT will resolve this issue. My bash profile does not contain the Rdkit path and it is the following:

PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

export PYTHONPATH

# added by Anaconda2 4.2.0 installer
export PATH="/Users/taufikridha/anaconda/bin:$PATH"

**Comment by KEHANG** [comment]
you can clean up your path and test `import rdkit` outside of `rmg_env` environment until you get `ImportError: no module named rdkit`

**Comment by tobikone** [comment]
Kehang,

I revised my path and the RMG works fine now. Thank you very much for your time.
