### ISSUE TITLE
carbon monoxide's adjacency list generation is incorrect

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-website#126]
The proper Adjacency list for CO is:

```
    1 C u0 p1 c-1 {2,T}
    2 O u0 p1 c+1 {1,T}
```

Imputing many of the acceptable names for the compound, like `[C-]#[O+]` an Adj list that throws an invalid adjacency list error. 

```
   1 C u0 p0 c-1 {2,T}
   2 O u0 p1 c+1 {1,T}
```

In addition, the drawing of CO with the proper adj list in [molecule search](http://rmg.mit.edu/molecule_search) is `-CO`, and I think this may arise from a similar issue.

**Comment by nyee** [comment]
This issue is closely related to the more major issue: ReactionMechanismGenerator/RMG-Py#489

**Comment by mliu49** [comment]
This appears to be fixed. Inputting `[C-]#[O+]` gives the correct adjacency list.
