### ISSUE TITLE
Error when I look at a kinetics result

### ISSUE THREAD

**Issue by rgillis8** [ReactionMechanismGenerator/RMG-website#131]
When I try and look at a specific entry of a kinetics result I get an error.

AssertionError at /database/kinetics/families/SubstitutionS/rate_rules/reactant1=multiplicity 2 1 C u0 p0 c0 {2,D} {3,S} {7,S} 2 C u0 p0 c0 {1,D} {4,S} {8,S} 3 C u0 p0 c0 {1,S} {6,D} {12,S} 4 C u0 p0 c0 {2,S} {5,D} {9,S} 5 C u0 p0 c0 {4,D} {6,S} {10,S} 6 C u0 p0 c0 {3,D} {5,S} {11,S} 7 C u1 p0 c0 {1,S} {13,S} {14,S} 8 H u0 p0 c0 {2,S} 9 H u0 p0 c0 {4,S} 10 H u0 p0 c0 {5,S} 11 H u0 p0 c0 {6,S} 12 H u0 p0 c0 {3,S} 13 H u0 p0 c0 {7,S} 14 H u0 p0 c0 {7,S} __reactant2=1 C u0 p0 c0 {3,S} {15,S} {19,S} {20,S} 2 C u0 p0 c0 {4,S} {16,S} {21,S} {22,S} 3 C u0 p0 c0 {1,S} {5,B} {6,B} 4 C u0 p0 c0 {2,S} {7,B} {8,B} 5 C u0 p0 c0 {3,B} {9,B} {23,S} 6 C u0 p0 c0 {3,B} {11,B} {27,S} 7 C u0 p0 c0 {4,B} {12,B} {28,S} 8 C u0 p0 c0 {4,B} {14,B} {32,S} 9 C u0 p0 c0 {5,B} {10,B} {24,S} 10 C u0 p0 c0 {9,B} {11,B} {25,S} 11 C u0 p0 c0 {6,B} {10,B} {26,S} 12 C u0 p0 c0 {7,B} {13,B} {29,S} 13 C u0 p0 c0 {12,B} {14,B} {30,S} 14 C u0 p0 c0 {8,B} {13,B} {31,S} 15 S u0 p2 c0 {1,S} {17,S} 16 S u0 p2 c0 {2,S} {18,S} 17 S u0 p2 c0 {15,S} {18,S} 18 S u0 p2 c0 {16,S} {17,S} 19 H u0 p0 c0 {1,S} 20 H u0 p0 c0 {1,S} 21 H u0 p0 c0 {2,S} 22 H u0 p0 c0 {2,S} 23 H u0 p0 c0 {5,S} 24 H u0 p0 c0 {9,S} 25 H u0 p0 c0 {10,S} 26 H u0 p0 c0 {11,S} 27 H u0 p0 c0 {6,S} 28 H u0 p0 c0 {7,S} 29 H u0 p0 c0 {12,S} 30 H u0 p0 c0 {13,S} 31 H u0 p0 c0 {14,S} 32 H u0 p0 c0 {8,S} __product1=1 C u0 p0 c0 {3,S} {16,S} {17,S} {18,S} 2 C u0 p0 c0 {4,S} {15,S} {19,S} {20,S} 3 C u0 p0 c0 {1,S} {5,B} {6,B} 4 C u0 p0 c0 {2,S} {7,B} {8,B} 5 C u0 p0 c0 {3,B} {9,B} {21,S} 6 C u0 p0 c0 {3,B} {11,B} {25,S} 7 C u0 p0 c0 {4,B} {12,B} {26,S} 8 C u0 p0 c0 {4,B} {14,B} {30,S} 9 C u0 p0 c0 {5,B} {10,B} {22,S} 10 C u0 p0 c0 {9,B} {11,B} {23,S} 11 C u0 p0 c0 {6,B} {10,B} {24,S} 12 C u0 p0 c0 {7,B} {13,B} {27,S} 13 C u0 p0 c0 {12,B} {14,B} {28,S} 14 C u0 p0 c0 {8,B} {13,B} {29,S} 15 S u0 p2 c0 {2,S} {16,S} 16 S u0 p2 c0 {1,S} {15,S} 17 H u0 p0 c0 {1,S} 18 H u0 p0 c0 {1,S} 19 H u0 p0 c0 {2,S} 20 H u0 p0 c0 {2,S} 21 H u0 p0 c0 {5,S} 22 H u0 p0 c0 {9,S} 23 H u0 p0 c0 {10,S} 24 H u0 p0 c0 {11,S} 25 H u0 p0 c0 {6,S} 26 H u0 p0 c0 {7,S} 27 H u0 p0 c0 {12,S} 28 H u0 p0 c0 {13,S} 29 H u0 p0 c0 {14,S} 30 H u0 p0 c0 {8,S} __product2=multiplicity 2 1 C u0 p0 c0 {2,S} {8,S} {9,S} {10,S} 2 C u0 p0 c0 {1,S} {3,B} {4,B} 3 C u0 p0 c0 {2,B} {5,B} {11,S} 4 C u0 p0 c0 {2,B} {7,B} {14,S} 5 C u0 p0 c0 {3,B} {6,B} {12,S} 6 C u0 p0 c0 {5,B} {7,B} {13,S} 7 C u0 p0 c0 {4,B} {6,B} {15,S} 8 S u0 p2 c0 {1,S} {16,S} 9 H u0 p0 c0 {1,S} 10 H u0 p0 c0 {1,S} 11 H u0 p0 c0 {3,S} 12 H u0 p0 c0 {5,S} 13 H u0 p0 c0 {6,S} 14 H u0 p0 c0 {4,S} 15 H u0 p0 c0 {7,S} 16 S u1 p2 c0 {8,S}
Was expecting one group estimate rate, not 0
Request Method:	GET
Request URL:	http://rmg.mit.edu/database/kinetics/families/SubstitutionS/rate_rules/reactant1%3Dmultiplicity%202%0A1%20%20C%20u0%20p0%20c0%20%7B2,D%7D%20%7B3,S%7D%20%7B7,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1,D%7D%20%7B4,S%7D%20%7B8,S%7D%0A3%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B6,D%7D%20%7B12,S%7D%0A4%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B5,D%7D%20%7B9,S%7D%0A5%20%20C%20u0%20p0%20c0%20%7B4,D%7D%20%7B6,S%7D%20%7B10,S%7D%0A6%20%20C%20u0%20p0%20c0%20%7B3,D%7D%20%7B5,S%7D%20%7B11,S%7D%0A7%20%20C%20u1%20p0%20c0%20%7B1,S%7D%20%7B13,S%7D%20%7B14,S%7D%0A8%20%20H%20u0%20p0%20c0%20%7B2,S%7D%0A9%20%20H%20u0%20p0%20c0%20%7B4,S%7D%0A10%20H%20u0%20p0%20c0%20%7B5,S%7D%0A11%20H%20u0%20p0%20c0%20%7B6,S%7D%0A12%20H%20u0%20p0%20c0%20%7B3,S%7D%0A13%20H%20u0%20p0%20c0%20%7B7,S%7D%0A14%20H%20u0%20p0%20c0%20%7B7,S%7D%0A__reactant2%3D1%20%20C%20u0%20p0%20c0%20%7B3,S%7D%20%7B15,S%7D%20%7B19,S%7D%20%7B20,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B4,S%7D%20%7B16,S%7D%20%7B21,S%7D%20%7B22,S%7D%0A3%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B5,B%7D%20%7B6,B%7D%0A4%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B7,B%7D%20%7B8,B%7D%0A5%20%20C%20u0%20p0%20c0%20%7B3,B%7D%20%7B9,B%7D%20%7B23,S%7D%0A6%20%20C%20u0%20p0%20c0%20%7B3,B%7D%20%7B11,B%7D%20%7B27,S%7D%0A7%20%20C%20u0%20p0%20c0%20%7B4,B%7D%20%7B12,B%7D%20%7B28,S%7D%0A8%20%20C%20u0%20p0%20c0%20%7B4,B%7D%20%7B14,B%7D%20%7B32,S%7D%0A9%20%20C%20u0%20p0%20c0%20%7B5,B%7D%20%7B10,B%7D%20%7B24,S%7D%0A10%20C%20u0%20p0%20c0%20%7B9,B%7D%20%7B11,B%7D%20%7B25,S%7D%0A11%20C%20u0%20p0%20c0%20%7B6,B%7D%20%7B10,B%7D%20%7B26,S%7D%0A12%20C%20u0%20p0%20c0%20%7B7,B%7D%20%7B13,B%7D%20%7B29,S%7D%0A13%20C%20u0%20p0%20c0%20%7B12,B%7D%20%7B14,B%7D%20%7B30,S%7D%0A14%20C%20u0%20p0%20c0%20%7B8,B%7D%20%7B13,B%7D%20%7B31,S%7D%0A15%20S%20u0%20p2%20c0%20%7B1,S%7D%20%7B17,S%7D%0A16%20S%20u0%20p2%20c0%20%7B2,S%7D%20%7B18,S%7D%0A17%20S%20u0%20p2%20c0%20%7B15,S%7D%20%7B18,S%7D%0A18%20S%20u0%20p2%20c0%20%7B16,S%7D%20%7B17,S%7D%0A19%20H%20u0%20p0%20c0%20%7B1,S%7D%0A20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A21%20H%20u0%20p0%20c0%20%7B2,S%7D%0A22%20H%20u0%20p0%20c0%20%7B2,S%7D%0A23%20H%20u0%20p0%20c0%20%7B5,S%7D%0A24%20H%20u0%20p0%20c0%20%7B9,S%7D%0A25%20H%20u0%20p0%20c0%20%7B10,S%7D%0A26%20H%20u0%20p0%20c0%20%7B11,S%7D%0A27%20H%20u0%20p0%20c0%20%7B6,S%7D%0A28%20H%20u0%20p0%20c0%20%7B7,S%7D%0A29%20H%20u0%20p0%20c0%20%7B12,S%7D%0A30%20H%20u0%20p0%20c0%20%7B13,S%7D%0A31%20H%20u0%20p0%20c0%20%7B14,S%7D%0A32%20H%20u0%20p0%20c0%20%7B8,S%7D%0A__product1%3D1%20%20C%20u0%20p0%20c0%20%7B3,S%7D%20%7B16,S%7D%20%7B17,S%7D%20%7B18,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B4,S%7D%20%7B15,S%7D%20%7B19,S%7D%20%7B20,S%7D%0A3%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B5,B%7D%20%7B6,B%7D%0A4%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B7,B%7D%20%7B8,B%7D%0A5%20%20C%20u0%20p0%20c0%20%7B3,B%7D%20%7B9,B%7D%20%7B21,S%7D%0A6%20%20C%20u0%20p0%20c0%20%7B3,B%7D%20%7B11,B%7D%20%7B25,S%7D%0A7%20%20C%20u0%20p0%20c0%20%7B4,B%7D%20%7B12,B%7D%20%7B26,S%7D%0A8%20%20C%20u0%20p0%20c0%20%7B4,B%7D%20%7B14,B%7D%20%7B30,S%7D%0A9%20%20C%20u0%20p0%20c0%20%7B5,B%7D%20%7B10,B%7D%20%7B22,S%7D%0A10%20C%20u0%20p0%20c0%20%7B9,B%7D%20%7B11,B%7D%20%7B23,S%7D%0A11%20C%20u0%20p0%20c0%20%7B6,B%7D%20%7B10,B%7D%20%7B24,S%7D%0A12%20C%20u0%20p0%20c0%20%7B7,B%7D%20%7B13,B%7D%20%7B27,S%7D%0A13%20C%20u0%20p0%20c0%20%7B12,B%7D%20%7B14,B%7D%20%7B28,S%7D%0A14%20C%20u0%20p0%20c0%20%7B8,B%7D%20%7B13,B%7D%20%7B29,S%7D%0A15%20S%20u0%20p2%20c0%20%7B2,S%7D%20%7B16,S%7D%0A16%20S%20u0%20p2%20c0%20%7B1,S%7D%20%7B15,S%7D%0A17%20H%20u0%20p0%20c0%20%7B1,S%7D%0A18%20H%20u0%20p0%20c0%20%7B1,S%7D%0A19%20H%20u0%20p0%20c0%20%7B2,S%7D%0A20%20H%20u0%20p0%20c0%20%7B2,S%7D%0A21%20H%20u0%20p0%20c0%20%7B5,S%7D%0A22%20H%20u0%20p0%20c0%20%7B9,S%7D%0A23%20H%20u0%20p0%20c0%20%7B10,S%7D%0A24%20H%20u0%20p0%20c0%20%7B11,S%7D%0A25%20H%20u0%20p0%20c0%20%7B6,S%7D%0A26%20H%20u0%20p0%20c0%20%7B7,S%7D%0A27%20H%20u0%20p0%20c0%20%7B12,S%7D%0A28%20H%20u0%20p0%20c0%20%7B13,S%7D%0A29%20H%20u0%20p0%20c0%20%7B14,S%7D%0A30%20H%20u0%20p0%20c0%20%7B8,S%7D%0A__product2%3Dmultiplicity%202%0A1%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B8,S%7D%20%7B9,S%7D%20%7B10,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B3,B%7D%20%7B4,B%7D%0A3%20%20C%20u0%20p0%20c0%20%7B2,B%7D%20%7B5,B%7D%20%7B11,S%7D%0A4%20%20C%20u0%20p0%20c0%20%7B2,B%7D%20%7B7,B%7D%20%7B14,S%7D%0A5%20%20C%20u0%20p0%20c0%20%7B3,B%7D%20%7B6,B%7D%20%7B12,S%7D%0A6%20%20C%20u0%20p0%20c0%20%7B5,B%7D%20%7B7,B%7D%20%7B13,S%7D%0A7%20%20C%20u0%20p0%20c0%20%7B4,B%7D%20%7B6,B%7D%20%7B15,S%7D%0A8%20%20S%20u0%20p2%20c0%20%7B1,S%7D%20%7B16,S%7D%0A9%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A10%20H%20u0%20p0%20c0%20%7B1,S%7D%0A11%20H%20u0%20p0%20c0%20%7B3,S%7D%0A12%20H%20u0%20p0%20c0%20%7B5,S%7D%0A13%20H%20u0%20p0%20c0%20%7B6,S%7D%0A14%20H%20u0%20p0%20c0%20%7B4,S%7D%0A15%20H%20u0%20p0%20c0%20%7B7,S%7D%0A16%20S%20u1%20p2%20c0%20%7B8,S%7D%0A
Django Version:	1.8.4
Exception Type:	AssertionError
Exception Value:	
Was expecting one group estimate rate, not 0
Exception Location:	/var/www/RMG-website/rmgweb/database/views.py in kineticsGroupEstimateEntry, line 1960
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/var/www/RMG-website/rmgweb',
 '/var/www/RMG-Py',
 '/opt/anaconda/envs/rmg_env/lib/python2.7/site-packages',
 '/opt/anaconda/envs/rmg_env/lib/python2.7/site-packages/gprof2dot-2015.2.3-py2.7.egg',
 '/opt/anaconda/envs/rmg_env/lib/python2.7/site-packages/pydot-1.2.2-py2.7.egg',
 '/opt/anaconda/envs/rmg_env/lib/python2.7/site-packages/scoop-0.7.2.0-py2.7.egg',
 '/opt/anaconda/envs/rmg_env/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/PyDAS-1.0.0-py2.7-linux-x86_64.egg',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client',
 '/opt/anaconda/envs/rmg_env/lib/python2.7/site-packages/',
 '/var/www/RMG-website',
 '/var/www/RMG-website/rmgweb',
 '/var/www/RMG-database',
 '/var/www/RMG-Py']
Server time:	Mon, 31 Oct 2016 13:23:22 -0400

**Comment by mliu49** [comment]
This link works now, though I'm not sure what the original issue was or what fixed it.
