### ISSUE TITLE
Web kinetic search returns reactions with species that are different than the search criteria

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-website#134]
Looking up `[O]C=C <=> O=C=C + H` in the kinetic search apparently finds 20 results for this exact reactions.
However, only results 1-5, 9, 10, 15-19 represent the correct reaction above, while the rest are for a different reactant with the same products (`O=C[CH2] <=> O=C=C + H`). Same issue when searching for this reaction in reverse. Same issue when searching for this second reactions.
Strange that different reactions appear under the same entry.

BTW, what happened to reaction number 20 (the search apparently found 20 results, yet only 19 are shown)?

**Comment by alongd** [comment]
One of the results in the above example (number 18) is RMG's rate rule for R_Add_MulBond for the desired `[O]C=C <=> O=C=C + H` reaction, yet clicking on it redirects to the rate rule for `O=C[CH2] <=> O=C=C + H`.

**Comment by mliu49** [comment]
The discrepancy between the number of results declared on the search page and the actual number of results is a known issue (#116), although the cause has not been investigated yet.

The different species is a resonance structure of your input, so the reactions and associated kinetics are equivalent. However, the website does not explicitly generate resonance structures during kinetics searches, so it's unclear why both structure appear, and will need to be looked into.

**Comment by alongd** [comment]
Right, I see the resonance. So this really IS a feature :)
Thanks!
