### ISSUE TITLE
Latex rendering issue for kinetics

### ISSUE THREAD

**Issue by KEHANG** [ReactionMechanismGenerator/RMG-website#136]
Some latex rendering issues associated with kinetics, see example [here](http://rmg.mit.edu/database/kinetics/reaction/reactant1=1%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B4,S%7D%20%7B5,S%7D%0A2%20H%20u0%20p0%20c0%20%7B1,S%7D%0A3%20H%20u0%20p0%20c0%20%7B1,S%7D%0A4%20H%20u0%20p0%20c0%20%7B1,S%7D%0A5%20H%20u0%20p0%20c0%20%7B1,S%7D%0A__reactant2=1%20C%20u0%20p1%20c0%20%7B2,S%7D%20%7B3,S%7D%0A2%20H%20u0%20p0%20c0%20%7B1,S%7D%0A3%20H%20u0%20p0%20c0%20%7B1,S%7D%0A__product1=multiplicity%202%0A1%20C%20u1%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B4,S%7D%0A2%20H%20u0%20p0%20c0%20%7B1,S%7D%0A3%20H%20u0%20p0%20c0%20%7B1,S%7D%0A4%20H%20u0%20p0%20c0%20%7B1,S%7D%0A__product2=multiplicity%202%0A1%20C%20u1%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B4,S%7D%0A2%20H%20u0%20p0%20c0%20%7B1,S%7D%0A3%20H%20u0%20p0%20c0%20%7B1,S%7D%0A4%20H%20u0%20p0%20c0%20%7B1,S%7D%0A). But it doesn't happen for some other kinetics see example [here](http://rmg.mit.edu/database/kinetics/reaction/reactant1=1%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B4,S%7D%20%7B5,S%7D%0A2%20H%20u0%20p0%20c0%20%7B1,S%7D%0A3%20H%20u0%20p0%20c0%20%7B1,S%7D%0A4%20H%20u0%20p0%20c0%20%7B1,S%7D%0A5%20H%20u0%20p0%20c0%20%7B1,S%7D%0A__reactant2=multiplicity%203%0A1%20C%20u2%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%0A2%20H%20u0%20p0%20c0%20%7B1,S%7D%0A3%20H%20u0%20p0%20c0%20%7B1,S%7D%0A__product1=multiplicity%202%0A1%20C%20u1%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B4,S%7D%0A2%20H%20u0%20p0%20c0%20%7B1,S%7D%0A3%20H%20u0%20p0%20c0%20%7B1,S%7D%0A4%20H%20u0%20p0%20c0%20%7B1,S%7D%0A__product2=multiplicity%202%0A1%20C%20u1%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B4,S%7D%0A2%20H%20u0%20p0%20c0%20%7B1,S%7D%0A3%20H%20u0%20p0%20c0%20%7B1,S%7D%0A4%20H%20u0%20p0%20c0%20%7B1,S%7D%0A). Would be worthwhile to find out the reason behind.

**Comment by rwest** [comment]
The absence of the `<input id="train" type="submit" value="Create training rate from average">` is causing a bug in the JavaScript. I haven't confirmed that this javascript bug is the only problem, nor have I looked into why the 'train' button is missing, but it is where I suggest you start looking...

**Comment by mliu49** [comment]
Thanks @rwest!! That was a very helpful suggestion.

The training button is designed to not appear if the reaction does not fit any of the reaction families. However, there was some javascript that was trying to find the button by id when it didn't exist, which caused jsmath to wait indefinitely. Will be fixed by 675b6a42cc21cab11416711a81ca2f6399aec3d4 once I update the website.
