### ISSUE TITLE
Error in kinetics search

### ISSUE THREAD

**Issue by bslakman** [ReactionMechanismGenerator/RMG-website#138]
When I search several reactions in the Kinetics search I get a ValueError. They are all feasible hydrocarbon reactions for hydrogen abstraction. i.e. propane + methyl --> propyl + methane

I get the following Exception location:
`/var/www/RMG-website/rmgweb/database/tools.py in getRMGJavaKinetics, line 622`

Kinetics search was working just yesterday, so I'm not sure what changed between then and now?

**Comment by mliu49** [comment]
It seems to be an issue with the RMG-Java server. I went ahead and just shut it down (for now). Kinetics search should work again.

I think there may have been some interference between the Java servers for the main and dev sites. I was working on the dev site yesterday.
