### ISSUE TITLE
server error thrown when looking at kinetics

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-website#145]
for [this reaction](http://rmg.mit.edu/database/kinetics/reaction/reactant1=multiplicity%203%0A1%20%20C%20u1%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B5,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B4,D%7D%20%7B6,S%7D%0A3%20%20C%20u1%20p0%20c0%20%7B1,S%7D%20%7B7,S%7D%20%7B8,S%7D%0A4%20%20C%20u0%20p0%20c0%20%7B2,D%7D%20%7B9,S%7D%20%7B10,S%7D%0A5%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A6%20%20H%20u0%20p0%20c0%20%7B2,S%7D%0A7%20%20H%20u0%20p0%20c0%20%7B3,S%7D%0A8%20%20H%20u0%20p0%20c0%20%7B3,S%7D%0A9%20%20H%20u0%20p0%20c0%20%7B4,S%7D%0A10%20H%20u0%20p0%20c0%20%7B4,S%7D%0A__reactant2=multiplicity%202%0A1%20H%20u1%20p0%20c0%0A__product1=multiplicity%202%0A1%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B5,S%7D%20%7B6,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B4,D%7D%20%7B7,S%7D%0A3%20%20C%20u1%20p0%20c0%20%7B1,S%7D%20%7B8,S%7D%20%7B9,S%7D%0A4%20%20C%20u0%20p0%20c0%20%7B2,D%7D%20%7B10,S%7D%20%7B11,S%7D%0A5%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A6%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A7%20%20H%20u0%20p0%20c0%20%7B2,S%7D%0A8%20%20H%20u0%20p0%20c0%20%7B3,S%7D%0A9%20%20H%20u0%20p0%20c0%20%7B3,S%7D%0A10%20H%20u0%20p0%20c0%20%7B4,S%7D%0A11%20H%20u0%20p0%20c0%20%7B4,S%7D%0A) I tried to look up the kinetics, for rate rules, but it threw a server error.  This occurred both on developer site and general branch. Other reactions seem to display properly.

**Comment by mliu49** [comment]
For some reason, the resonance structure seems to be changing. The search request was for [CH2][CH]C=C, but the result displayed is for [CH2]C=C[CH2], which cannot undergo R_Recombination to give the desired product. This is an interesting bug... Thanks for posting it.

**Comment by goldmanm** [comment]
I am currently looking into some more reaction degeneracy issues and will likely be modifying `family.generate reactions` to take in entire species objects instead of molecule. This will likely fit in after `reactBenzene` PR and hopefully incorporate `newDegeneracies`. This will reduce the number of duplicate reactions sent through the entire system and allow us greater flexibility in keeping important duplicates in the future.

Do you think this modification would help with the issue at hand on the website side (of course we'd need to modify the website a bit to get this to work)?

**Comment by mliu49** [comment]
I converted generateReactions to use species instead of molecules [here](https://github.com/mliu49/RMG-Py/commits/reactBenzeneTest) to fix issues with reaction isomorphism matching.

However, the website uses it's own generateReactions method, located in the RMG-website code, so modifying RMG-Py won't help.

**Comment by goldmanm** [comment]
That looks really great! Will this be in the same pull request your 
`reactBenzene`?

**Comment by mliu49** [comment]
I'm planning to put it with degeneracy fixes, which will come after reactBenzene.

**Comment by mliu49** [comment]
This seems to work now. There have been a number of changes to reaction generation in RMG-Py and RMG-website, so I think those have addressed this bug.
