### ISSUE TITLE
Mathjax CDN shutting down

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-website#147]
https://www.mathjax.org/cdn-shutting-down/

Not sure if we were using this CDN or not (should check) but even if not we might want to consider the alternatives mentioned in the announcement

**Comment by mliu49** [comment]
We've switched to MathJax following #162 and are using one of their recommended CDNs. It seems that jsMath, which we were previously using, is no longer being developed and has been replaced by MathJax.
