### ISSUE TITLE
Allow access to rmg-website from external host (not 127.0.0.1)

### ISSUE THREAD

**Issue by wedsall** [ReactionMechanismGenerator/RMG-website#149]
Hello,
 Can you please tell me how to allow RMG-website to listen on an interface other than 127.0.0.1? We would like to access it in a client-server fashion.

Thanks
William

**Comment by rwest** [comment]
Hi. If you're following the instructions on the [wiki](https://github.com/ReactionMechanismGenerator/RMG-Py/wiki/Setting-up-RMG-website)  and doing `python manage.py runserver`, note that is only really intended for testing things out - it uses a minimal web server written in python. To actually deploy a real server, I recommend using something like Apache, and WSGI. There's an example configuration file in [RMG-website/apache/django.wsgi.example](https://github.com/ReactionMechanismGenerator/RMG-website/blob/master/apache/django.wsgi.example) and helpful instructions hosted by Django project at https://docs.djangoproject.com/en/1.11/howto/deployment/wsgi/modwsgi/  and other tutorials in places like https://www.digitalocean.com/community/tutorials/how-to-serve-django-applications-with-apache-and-mod_wsgi-on-ubuntu-14-04
