### ISSUE TITLE
How to convert Lennard-Jones well-depth to appropriate units?

### ISSUE THREAD

**Issue by bryanwweber** [ReactionMechanismGenerator/RMG-website#157]
The units given for the Lennard-Jones well-depth (epsilon) on a page for a molecule are J/mol [example](http://rmg.mit.edu/database/transport/molecule/1%20O%20u0%20p2%20c0%20%7B2,S%7D%20%7B5,S%7D%0A2%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B3,S%7D%20%7B6,S%7D%20%7B7,S%7D%0A3%20O%20u0%20p2%20c0%20%7B2,S%7D%20%7B4,S%7D%0A4%20O%20u0%20p2%20c0%20%7B3,S%7D%20%7B8,S%7D%0A5%20H%20u0%20p0%20c0%20%7B1,S%7D%0A6%20H%20u0%20p0%20c0%20%7B2,S%7D%0A7%20H%20u0%20p0%20c0%20%7B2,S%7D%0A8%20H%20u0%20p0%20c0%20%7B4,S%7D%0A), but the CHEMKIN format input file expects epsilon/k_b in units of K. I'm not sure how to do the conversion, since k_b has units of J/K and there ends up being an extra dimension of moles. If I ignore that, I get ridiculous answers on the order of 10**26. What are the correct units/conversion here?

Thank you!

**Comment by mliu49** [comment]
I think the missing factor is Avogadro's constant, to convert from moles to molecules. When saving tran.dat files, RMG divides epsilon by R, the gas constant, which is equivalent to k_b*Avogadro's constant.

**Comment by bryanwweber** [comment]
OK that gives me a reasonable number (507 K for the example I linked to before). Is there any way to indicate this on the web interface?
