### ISSUE TITLE
Triple bond sign (#) isn't recognized by the Molecule Search tool

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-website#158]
Typing `C#C` in molecule search gives CH4, and typing `N#N` gives NH3.
Seems like the molecule search tool treats `#` and everything after it as a comment.
(Triple bonds in SMILES still work on current RMG master, though)

**Comment by mliu49** [comment]
I've noticed this too. I'm pretty sure that the fix I made for the InChI issue broke SMILES (86ce991055ca1cfd35bf8c92e99735fac9ad51cc). I might just switch back to using the `escape()` function we were using before, despite the fact that it's generally not recommended.

**Comment by mliu49** [comment]
This should be fixed. I switched back to using `escape()` for now.
