### ISSUE TITLE
The page of "Torsional degrees of freedom" cannot be opened.

### ISSUE THREAD

**Issue by jimchu10** [ReactionMechanismGenerator/RMG-website#160]
The error I got:
System Message: WARNING/2 (/home/mark/workspace/RMG-Py/documentation/source/reference/statmech/hinderedrotor.rst, line 5)

autodoc: failed to import class ‘HinderedRotor’ from module ‘rmgpy.statmech’; the following exception was raised: Traceback (most recent call last): File “/home/mark/anaconda3/lib/python3.6/site-packages/Sphinx-1.5.1-py3.6.egg/sphinx/ext/autodoc.py”, line 547, in import_object __import__(self.modname) File “/home/mark/workspace/RMG-Py/rmgpy/statmech/__init__.py”, line 31, in <module> from .translation import Translation, IdealGasTranslation ImportError: dynamic module does not define module export function (PyInit_translation)

**Comment by mliu49** [comment]
This was an issue with the RMG-Py documentation, and has since been fixed.
