### ISSUE TITLE
Missing figures in RMG Kinetics Families

### ISSUE THREAD

**Issue by xiaoruiDong** [ReactionMechanismGenerator/RMG-website#169]
When looking at RMG Kinetics Families, several families are missing their figure representation. It is mainly due to lose image in the static.

**Comment by mliu49** [comment]
Good catch! The missing ones are all newly created families. I'll work on creating the missing images.

**Comment by mliu49** [comment]
I've made a new branch with the missing images added. Could you test locally to make sure they all show up properly?

**Comment by xiaoruiDong** [comment]
@mliu49 Sure, I will test is soon.
