### ISSUE TITLE
merge tool did not work, get "Gateway Timeout"

### ISSUE THREAD

**Issue by shenghuiqin** [ReactionMechanismGenerator/RMG-website#174]
hi, there,
I tried to merge two models using the merge tool, but tried many times only get:
"Gateway Timeout
The gateway did not receive a timely response from the upstream server or application."
what should i do?

**Comment by mliu49** [comment]
It's possible that your models are too large for the website to process in a reasonable time. I would suggest running the mergeModels script locally if you can install RMG.

http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/modules/mergeModels.html

**Comment by shenghuiqin** [comment]
ok, great, thank you!
