### ISSUE TITLE
RMG website test failure

### ISSUE THREAD

**Issue by xiaoruiDong** [ReactionMechanismGenerator/RMG-website#176]
All test failed according to the same error same issue:
`Cannot convert str to rmgpy.kinetics.uncertainties.RateUncertainty`

It seems like to be a RMG problem. Probably, we need to change the RMG build in Travis or something like that?

**Comment by mliu49** [comment]
Yes, this is an RMG-Py issue. It has been identified and a fix is contained in ReactionMechanismGenerator/RMG-Py#1705.
