### ISSUE TITLE
Molecule search doesn't find adjacency list with species name

### ISSUE THREAD

**Issue by ajocher** [ReactionMechanismGenerator/RMG-website#179]
Molecule search doesn't find adjacency list with species name in the 'species identifier' field.

I tried the default 2,3 dimethyl hexan-4-ol and several other species such as benzene and got these errors:
Not Found
Could not identify 2,3 dimethyl hexan-4-ol. NCI resolver responded with <urlopen error [Errno 101] Network is unreachable>.

Not Found
Could not identify benzene. NCI resolver responded with <urlopen error [Errno 101] Network is unreachable>.

**Comment by mliu49** [comment]
I also saw this earlier. Seems like the NCI resolver is down. I don't think there's much we can do about it.

**Comment by xiaoruiDong** [comment]
I tried the newest version RMG-website, and it seemed like the NCI resolver is back. The given examples are now working. Thanks.
