### ISSUE TITLE
Improve error handling for MoleculeEntry page

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-website#187]
The MoleculeEntry page uses template tags to generate InChI and SMILES strings while building the template ([see here](https://github.com/ReactionMechanismGenerator/RMG-website/blob/master/rmgweb/database/templates/moleculeEntry.html#L82)). However, this means there's no error handling, so if InChI or SMILES generation fails, the page crashes with an internal server error.

This should be updated to be like the MoleculeSearch page, which generates the identifiers in the view and passes them to the template via context ([see here](https://github.com/ReactionMechanismGenerator/RMG-website/blob/master/rmgweb/database/views.py#L2373)). This lets us catch errors and then simply display that we failed to generate an identifier instead of breaking the entire page.

**Comment by xiaoruiDong** [comment]
Thanks, @mliu49. Thank you for telling me what results in tones of errors about molecule entry. I will take a look and figure it out.
