### ISSUE TITLE
Post-Installation Tests Fail on HPC Cluster

### ISSUE THREAD

**Issue by mefuller** [ReactionMechanismGenerator/RMG-website#189]
I am attempting to install and run RMG locally on my university's HPC cluster (CentOS 7.7).
Compilation of RMG appears to work just fine, but most of the tests fail.

The errors from the failed tests are one of the following:
1) ERROR: Failure: AttributeError (type object 'rmgpy.kinetics.model.TunnelingModel' has no attribute '__reduce_cython__')
2) ERROR: Failure: ImportError (/rwthfs/rz/cluster/home/db011307/RMG/RMG-Py/rmgpy/species.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _intel_fast_memcmp)
3) ERROR: Failure: ImportError (/rwthfs/rz/cluster/home/db011307/RMG/RMG-Py/rmgpy/chemkin.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _intel_fast_memmove)

**Comment by mliu49** [comment]
Are you trying to install just RMG or set up RMG website? This issue might be more appropriate in the https://github.com/ReactionMechanismGenerator/RMG-Py repo.

I think we've previously encountered issues with installing RMG on another CentOS HPC cluster. In that case, they ended up installing RMG via a Docker image.
