### ISSUE TITLE
Reset/find user account information

### ISSUE THREAD

**Issue by mefuller** [ReactionMechanismGenerator/RMG-website#190]
The login form for the RMG website appears to lack an option to recover lost usernames  and/or reset passwords.

**Comment by xiaoruiDong** [comment]
Thank you for bringing it up, and I agree that it is desirable. I've been working on this for a while, and I will try to have it functioning and available.

**Comment by xiaoruiDong** [comment]
> The login form for the RMG website appears to lack an option to recover lost usernames and/or reset passwords.

@mefuller. Please take a look at the latest RMG website. We implement password reset function. I will think about enabling logging-in with email in the next stage. Thanks.
