### ISSUE TITLE
AttributeError: 'ThermoDatabase' object has no attribute 'binding_energies'

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-website#208]
Click the "1 result" link from [this kinetics search](https://rmg.mit.edu/database/kinetics/results/reactant1=multiplicity%203%0D%0A1%20O%20u1%20p2%20c0%20%7B2,S%7D%0D%0A2%20O%20u1%20p2%20c0%20%7B1,S%7D__reactant2=1%20X%20u0__res=True) and you get Sorry, an internal error was encountered.
`AttributeError: 'ThermoDatabase' object has no attribute 'binding_energies'`.

This wasn't a problem until yesterday, when we updated RMG-Py and RMG-database (but not RMG-website)

The current Git commits on which the website is operating are as follows:

Repository | Commit | Date
-- | -- | --
RMG-Py | 6146e3e1c90b583bcc3b15d0afea98947e1bd1efMerge branch 'Metal_Attributes'. Closes #2025. Needs RMG-database update.Thanks @mazeau for this contribution, and to David, Katrin, and allthe other reviewers and helpers.There's an update to the RMG-database required. | Mon, 8 Feb 2021 14:02:40 -0500
RMG-database | 5a426151722f4a1cb70d4132fe7cc5d1dc3eba8bMerge branch 'Metal_Attributes'. Closes #387. Requires RMG-Py update.Thanks @mazeau and @kblondal for this contribution,and David and all the other reviewers.Requires an update to RMG-Py, which was pull requesthttps://github.com/ReactionMechanismGenerator/RMG-Py/pull/2025merged in 6146e3e1c90b583bcc3b15d0afea98947e1bd1ef | Mon, 8 Feb 2021 14:06:27 -0500
RMG-website | 4a00980943d57204863266d93f7648016a02d081Merge pull request #207 from ReactionMechanismGenerator/devAdd loading image and recommendations in kinetic search | Tue, 1 Dec 2020 11:07:22 -0500

Both the RMG-Py and the RMG-database have the new Metal_Attributes pull request, but perhaps the RMG-website is not loading the `ThermoDatabase` correctly or entirely?
@mazeau is there anything special that should be done to load the new metal attributes?

Or is it expecting the `binding_engergies` attribute on some other type of ThermoDatabase object?

Would probably need a stack trace to figure that out.

**Comment by davidfarinajr** [comment]
I think I know the issue.  We used to `set_delta_atomic_ads` when we initialized thermo database, but now you need to call `set_binding_energies` to give thermoDB binding energies attr which is then used to get thermo for adsorbates.  We should probably give it Pt111 binding energies when initializing. We can't `set_binding_energies` on `init` since you need to have `MetalDB` loaded.  Sorry we missed this somehow in code review and the unit tests didn't catch it
