### ISSUE TITLE
Molecule Search failing to populate adjacency list

### ISSUE THREAD

**Issue by mefuller** [ReactionMechanismGenerator/RMG-website#210]
Not sure if this is RMG or another component (no alternatives available presently to test), but on Ubuntu 20.04 LTS in Firefox 85, the Molecule Search is no longer populating the adjacency list for me from a SMILES input (or other identifier)

**Comment by jonwzheng** [comment]
Hi, please try using Molecule Search again and let us know if you're still running into the same problem.

**Comment by mefuller** [comment]
It is working on Fedora 33 / Firefox 85, so I am assuming there is something system-specific on my end and not RMG-web that is causing the problem

**Comment by xiaoruiDong** [comment]
> It is working on Fedora 33 / Firefox 85, so I am assuming there is something system-specific on my end and not RMG-web that is causing the problem

Thank you for reporting this. We have tested on Ubuntu 20.04 with Firefox 85, Mac OS Big Sur Chrome 88 / Microsoft Edge 88, as well as web browsers on mobile devices, but we cannot reproduce your issue. So, this seems to be a machine-specific problem, and we suggest you retry (maybe after reboot your web browser or OS) and let us know if that problem persists. Thanks!
