### ISSUE TITLE
Feature request: hyperlinks to thermo group contribution entries.

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-website#214]
When looking at the thermo for a molecule like [this](https://rmg.mit.edu/database/thermo/molecule/1%20O%20u0%20p2%20c0%20%7B3,S%7D%20%7B5,S%7D%0A2%20O%20u0%20p2%20c0%20%7B3,D%7D%0A3%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B2,D%7D%20%7B4,S%7D%0A4%20X%20u0%20p0%20c0%20%7B3,S%7D%0A5%20X%20u0%20p0%20c0%20%7B1,S%7D%0A)  you see in the Group Additivity section the comment like 
> Comments: Gas phase thermo for CO2 from Thermo library: DFT_QCI_thermo. Adsorption correction: + Thermo group additivity estimation: adsorptionPt111(C=\*RO-\*)

It would be nice if those groups names were hyperlinks through to the entries in the group database so you could find out more about them.  Maybe even library entries could by hyperlinked. A bit like:

> Comments: Gas phase thermo for CO2 from Thermo library: [DFT_QCI_thermo](https://rmg.mit.edu/database/thermo/libraries/DFT_QCI_thermo/19/). Adsorption correction: + Thermo group additivity estimation: [adsorptionPt111(C=\*RO-\*)](https://rmg.mit.edu/database/thermo/groups/adsorptionPt111/65/)

**Comment by jonwzheng** [comment]
Implemented in #223. Thanks for the suggestion!
