### ISSUE TITLE
Reactions in Surface_Bidentate_Dissociation family show KeyError: '1' 

### ISSUE THREAD

**Issue by Tingchenlee** [ReactionMechanismGenerator/RMG-website#215]
The following reactions on RMG-website show an error  message of " KeyError:'1' "
![image](https://user-images.githubusercontent.com/56702445/110973390-3327a280-832b-11eb-8bf6-91bca59449cd.png)

**Comment by xiaoruiDong** [comment]
@Tingchenlee. Thanks for reporting this issue. RMG-website does have problem rendering units that are `1/XXXX`. I will look into that.

**Comment by ChrisBNEU** [comment]
it looks like only one rule in one surface family has "1/s" for it's units, so we can correct this pretty [easily](https://github.com/ReactionMechanismGenerator/RMG-database/tree/units_issue). there are a number of other issues with the retroene reaction family (they all have A factor units of 1/s), so we can either change all of those units or we can program better handling so we can accept 1/s or s^-1. That could be handled in RMG or the website. in the website code the problem occurrs when we evaluate
```
dimensionality[UNIT_TYPES[unit]] = power
```
and the UNIT_TYPES[unit] is given a 1 (from 1/s)
