### ISSUE TITLE
Duplicate Surface Reactions with the Same Kinetic in Kinetic Search(Surface_Abstraction_vdW family)

### ISSUE THREAD

**Issue by Tingchenlee** [ReactionMechanismGenerator/RMG-website#218]
The Kinetic Search of this reaction in the Surface_Abstraction_vdW family shows two identical templates of the RMG-Py rate rules. 

Fig 1.
![image](https://user-images.githubusercontent.com/56702445/113598528-41579e80-960b-11eb-93c0-dbf105d1c6da.png)
It seems like the family template matches both ```*2 O``` and ```*3 O ```
```
multiplicity [1]
1 *1 Xv u0 p0 c0
2 *2 O  u0 p2 c0 {3,S} {5,S}
3 *3 O  u0 p2 c0 {2,S} {4,S}
4    H  u0 p0 c0 {3,S}
5    H  u0 p0 c0 {2,S}
``` 

I'm not sure if we need to relate the reaction rate to the degeneracy here.
This issue didn't show up in ```N2H4``` and ```C2H2``` reactions

Fig 2.
![image](https://user-images.githubusercontent.com/56702445/113601517-6e0db500-960f-11eb-83f4-3c8eededbc46.png)
Fig 3.
![image](https://user-images.githubusercontent.com/56702445/113601617-91d0fb00-960f-11eb-95fc-3b1c0aadfb70.png)

**Comment by xiaoruiDong** [comment]
@Tingchenlee, thank you for reporting this issue. I think it might be the desirable behavior of RMG to include both rates as the overall rate for this reaction. This reaction can undergo two different paths with different transition state geometries. I made a draft below. Although it may need further check by actual QM calculations, the conclusion from 2D graph indicates there are two different ways.

 ![image](https://user-images.githubusercontent.com/35771233/114913744-2d6c2380-9de7-11eb-93c0-a208efa8c637.png)
