### ISSUE TITLE
RMG kinetics search cannot perform kinetics search

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-website#229]
Searching for CH4 + OH, or other simple reactions I expect RMG to know about, results in the message:

![image](https://user-images.githubusercontent.com/16158262/128836657-7592fd9d-7bef-408f-9e0b-9b25cff5c5c2.png)

Is the search temporally down?

**Comment by xiaoruiDong** [comment]
> Searching for CH4 + OH, or other simple reactions I expect RMG to know about, results in the message:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/16158262/128836657-7592fd9d-7bef-408f-9e0b-9b25cff5c5c2.png)
> 
> 
> 
> Is the search temporally down?
> 
> 
> 
> 

Hi Alon, Jon and I have difficulty in reproducing your issue. Can you let us know how did you do the search? Have you tried 'C' and '[OH]' instead of CH4 and OH? Thanks!

**Comment by xiaoruiDong** [comment]
I reach the same page if I search with 'C' and 'OH', is that what you tried?

**Comment by alongd** [comment]
Hi, I tried with proper SMILES (`C` and `[OH]`). I still get the same "no results found" message.
Strange that we both see different things. I tried using a VPN connecting through North America (NY), and I confirm that this issue isn't location-based (got the same message through the VPN)

Let's keep an eye on it. I'll keep trying to see if anything changes. Please see if you observe any glitches as well.

**Comment by jonwzheng** [comment]
Hi Alon, thanks for posting this. Hmm, could you share what link you get when you make the search with `C` and `[OH]` in the kinetics search? Do you get the following page:

https://rmg.mit.edu/database/kinetics/results/reactant1=1%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B4,S%7D%20%7B5,S%7D%0D%0A2%20H%20u0%20p0%20c0%20%7B1,S%7D%0D%0A3%20H%20u0%20p0%20c0%20%7B1,S%7D%0D%0A4%20H%20u0%20p0%20c0%20%7B1,S%7D%0D%0A5%20H%20u0%20p0%20c0%20%7B1,S%7D__reactant2=multiplicity%202%0D%0A1%20O%20u1%20p2%20c0%20%7B2,S%7D%0D%0A2%20H%20u0%20p0%20c0%20%7B1,S%7D__res=True

**Comment by alongd** [comment]
The feature's working again for me, closing issue (thanks for the assistance!)
