### ISSUE TITLE
KineticsError: Unable to calculate degeneracy when opening page https://rmg.mit.edu/database/kinetics/families/

### ISSUE THREAD

**Issue by xiaoruiDong** [ReactionMechanismGenerator/RMG-website#241]
When opening https://rmg.mit.edu/database/kinetics/families/, I got the following error: 

rmgpy.exceptions.KineticsError: Unable to calculate degeneracy for reaction [CH2]C=CC=CC=C <=> <Molecule "[CH]1C=CC=CCC1"> in reaction family Intra_R_Add_Endocyclic. Expected 1 reaction but generated 0

Potentially, there is something wrong with the Intra_R_Add_Endocyclic family in the database.

**Comment by jonwzheng** [comment]
Hi Xiaorui, do you still get this error when you visit the site? I don't get an error message when I visit the site. (Ubuntu 20.04 on Firefox 99.0x64)

**Comment by xiaoruiDong** [comment]
Thanks! I didn't get the error with another try today. I will close the issue if I don't run into it or I haven't heard from others about this.
