### ISSUE TITLE
RMG is taking its database from a different location 

### ISSUE THREAD

**Issue by purkun01** [ReactionMechanismGenerator/RMG-website#256]
Hello RMG developers,

I was trying to run some scripts when I realized that RMG is taking it's global settings from the location given below 

ananconda3/envs/rmg_env/share/rmgdatabase

and not from the database where I am making my changes (i.e. RMG-database which I pulled from github).

Is there anyway to make RMG take it's data from the RMG-database and not from the rmgdatabase specified in the above path?

**Comment by alongd** [comment]
Hi, did you install RMG from binaries, of from source?

**Comment by purkun01** [comment]
Installation by source using anaconda environment for linux based systems i.e. developer installation
