### ISSUE TITLE
create RMG-Java Kinetics Library

### ISSUE THREAD

**Issue by wenjunzhong** [ReactionMechanismGenerator/RMG-website#259]
Hello RMG developers,
when  I create RMG-Java Kinetics Library,the error message is as follows:IndexError: string index out of range.Any idea on how to resolve this problem?

**Comment by rwest** [comment]
Hi. I'm afraid we stopped maintaining or supporting RMG-Java many years ago now. Probably the solution here is to remove the feature rather than fix the feature to export RMG-Java Kinetics Library. Can you point us to where it is? How do you get to that error message?

**Comment by wenjunzhong** [comment]
Hi,I found it on the RMG website. This is the exact location: https://rmg.mit.edu/tools/java_kinetics_library

**Comment by jonwzheng** [comment]
Sorry for the late response - we no longer support RMG-Java in RMG-Py and should remove the feature from the website as well (#281).
