### ISSUE TITLE
Evaluate NASA Polynomial Tool on RMG Website fails

### ISSUE THREAD

**Issue by Sayandeep00** [ReactionMechanismGenerator/RMG-website#263]
Tried running this with Chemkin NASA polynomial output from molecule search in RMG for C1CC[CH]CC1. When trying to use the evaluate tool I get the following errors,

ValueError: could not convert string to float: 'est'  - Benson-type

IndexError: string index out of range - JetSurf

**Comment by jonwzheng** [comment]
Hi Sayandeep, my apologies for the late response. I can't recreate this from my end - have you tried using the tool _without_ the commented header? I.e. remove the line that starts with exclamation points.  Example:
```
C6H11                   C   6H  11          G   100.000  5000.000 1058.04      1
 6.31939904E+00 4.60862991E-02-2.01054483E-05 3.90418280E-09-2.80766403E-13    2
 1.75644823E+03-1.28640922E+01 2.42567888E+00 1.91772478E-02 7.70631322E-05    3
-9.45092942E-08 3.17599954E-11 4.91048537E+03 1.71519368E+01                   4
```
