### ISSUE TITLE
OSError: [Errno 28]

### ISSUE THREAD

**Issue by Filozofafa** [ReactionMechanismGenerator/RMG-website#268]
Good afternoon! An error occurs when trying to use the tools on the RMG website - https://rmg.mit.edu/tools/
When trying, for example, to visualize a Chemkin file, the following error appears:

OSError: [Errno 28] No space left on device: '/var/www/RMG-website/rmgweb/media/rmg/tools/chemkin'

I tried to run the tool on several other computers - the result is still the same.

**Comment by jonwzheng** [comment]
We think we've cleared up the hardware issue from our side now. Could you please confirm whether it's working for you now? Thanks!

**Comment by Filozofafa** [comment]
> We think we've cleared up the hardware issue from our side now. Could you please confirm whether it's working for you now? Thanks!

Everything works! Super! Thank you very much!
