### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by DiegoGuajardoP** [ReactionMechanismGenerator/RMG-website#274]
Hi! I am trying to to merge two mechanisms and I get the following error:
"IndexError: list index out of range" I used the websites merging tool so I dont have any othe additional information on how to 
find out what went wrong.
Thanks

**Comment by DiegoGuajardoP** [comment]
Hi Jon, thanks for replying. Here are the dictionaries I am using. 
[Krishna_Dictionary.txt](https://github.com/ReactionMechanismGenerator/RMG-website/files/14365191/Krishna_Dictionary.txt)
[CRECK_Toluene_Dictionary.txt](https://github.com/ReactionMechanismGenerator/RMG-website/files/14365192/CRECK_Toluene_Dictionary.txt)
[CRECK_Heptane_Dictionary.txt](https://github.com/ReactionMechanismGenerator/RMG-website/files/14365193/CRECK_Heptane_Dictionary.txt)

**Comment by jonwzheng** [comment]
Hi Diego,

My sincere apologies for the late reply. The merge mechanisms feature requires each model's Chemkin file (see [documentation](https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/output.html)) - are you also providing these to the website?

Second, if you have `RMG-Py` installed on your computer, have you tried using the `scripts/mergeModels` feature to try on your local machine, as described on [this page](https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/modules/mergeModels.html)?
