### ISSUE TITLE
Entering "O2" in the kinetics search leads to O=O not .O-O.

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-website#46]
As all our kinetics are defined for molecular oxygen being the triplet (Oj-Oj) not the singlet (O=O) I think the behaviour of the form when you enter "O2" is counterintuitive and will trip people up.

As an aside - I notice the coe.neu.edu version of the website draws both these structures as O<sub>2</sub>, which makes it even harder to see what's happening. Not sure how/when we diverged, but the mit.edu site is drawing them differently.

**Comment by mliu49** [comment]
Both singlet and triplet forms are now drawn as O<sub>2</sub>. Searching 'oxygen' or 'O2' or '[O][O]' all give the triplet form, as desired, and 'O=O' is the only way to get the singlet form. It seems that this issue can be closed now.
