### ISSUE TITLE
Molecule search unable to find some CAS number.

### ISSUE THREAD

**Issue by chatelak** [ReactionMechanismGenerator/RMG-website#76]
Just as information, I don't know If we can really to something to fix it. Like this it will be a least documented.
It is just  to point out some strange behavior in the molecule search tool. 

Some CAS number are just not recognized but as suggested @connie  it is because they are not listed in NIST and web tool is based on NIST database.
I found three different cases:
First list: (not working but does not exist on nist so it makes sense)
2143-69-3
1981-80-2
6067-68-1
15552-77-9
67152-18-5
108179-96-0
86181-68-2
687-97-4
2810-61-9
63707-54-0
309966-76-5
Most of them are radicals, I don't know if it is a reason why their representations are hard to find in litterature. I finally found most of them thanks to their name and "CAS #" in Burcat's database.

Second list: (not recognized at the beginning and then find it after drawing the molecule)
2143-58-0 (exists on NIST but no representation given)
436-51-4 (does not exit on NIST)

Third list:
53561-65-2 (exist on NIST and not found by the tool)

The second list behavior is really strange:
The second list is species unrecognized at the beginning, but after giving the adjacency list by hand, the tool displayed some informaiton on the molecule instead of an error (as it displayed for the first list). And I was very surprised to find my CAS number in those information. And of course after that the CAS number is now recognized. After finding this for the first molecuel,  I tried to import 3 times a CAS number before trying to draw the molecule by hand. And I found the same behavior a second time with: (436-51-4).

The third list is just because were are not dynamically linked to nist database. So it is not really a problem neither.

**Comment by jonwzheng** [comment]
Closing stale issue. BTW, see #258 - there is a somewhat more robust API for accessing CAS numbers.
The best way of searching CAS is using CAS SciFinder, but API access is restricted for our educational license. You can still use CAS SciFinder to do manual search of your molecule-of-interest and get its SMILES string, however.
