### ISSUE TITLE
Aromatics drawings inconsistent

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-website#78]
A kinetics search for [OH] abstracting from 3-hydroxybenzaldehyde shows this list of reactions, drawn kekulized
![screen shot 2015-03-03 at 5 31 47 pm](https://cloud.githubusercontent.com/assets/93807/6473975/358b5ad0-c1cb-11e4-946c-e6f7286ba443.png)
but when I click on one (I was interested in the last one) it is drawn as aromatic rings

![screen shot 2015-03-03 at 5 30 37 pm](https://cloud.githubusercontent.com/assets/93807/6473988/4d2b4bb4-c1cb-11e4-857a-beb6a4c3bfe0.png)

(then, when you click on the [Result #1 - H_Abstraction (RMG-Py rate rules)](http://rmg.mit.edu/database/kinetics/families/H_Abstraction/rate_rules/reactant1=1%20C%20u0%20p0%20c0%20%7B3,B%7D%20%7B4,B%7D%20%7B7,S%7D;2%20C%20u0%20p0%20c0%20%7B3,B%7D%20%7B5,B%7D%20%7B8,S%7D;3%20C%20u0%20p0%20c0%20%7B1,B%7D%20%7B2,B%7D%20%7B12,S%7D;4%20C%20u0%20p0%20c0%20%7B1,B%7D%20%7B6,B%7D%20%7B11,S%7D;5%20C%20u0%20p0%20c0%20%7B2,B%7D%20%7B6,B%7D%20%7B9,S%7D;6%20C%20u0%20p0%20c0%20%7B4,B%7D%20%7B5,B%7D%20%7B10,S%7D;7%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B13,D%7D%20%7B14,S%7D;8%20O%20u0%20p2%20c0%20%7B2,S%7D%20%7B15,S%7D;9%20H%20u0%20p0%20c0%20%7B5,S%7D;10%20H%20u0%20p0%20c0%20%7B6,S%7D;11%20H%20u0%20p0%20c0%20%7B4,S%7D;12%20H%20u0%20p0%20c0%20%7B3,S%7D;13%20O%20u0%20p2%20c0%20%7B7,D%7D;14%20H%20u0%20p0%20c0%20%7B7,S%7D;15%20H%20u0%20p0%20c0%20%7B8,S%7D;__reactant2=multiplicity%202;1%20O%20u1%20p2%20c0%20%7B2,S%7D;2%20H%20u0%20p0%20c0%20%7B1,S%7D;__product1=1%20O%20u0%20p2%20c0%20%7B2,S%7D%20%7B3,S%7D;2%20H%20u0%20p0%20c0%20%7B1,S%7D;3%20H%20u0%20p0%20c0%20%7B1,S%7D;__product2=multiplicity%202;1%20C%20u0%20p0%20c0%20%7B3,B%7D%20%7B4,B%7D%20%7B7,S%7D;2%20C%20u0%20p0%20c0%20%7B3,B%7D%20%7B5,B%7D%20%7B8,S%7D;3%20C%20u0%20p0%20c0%20%7B1,B%7D%20%7B2,B%7D%20%7B12,S%7D;4%20C%20u0%20p0%20c0%20%7B1,B%7D%20%7B6,B%7D%20%7B11,S%7D;5%20C%20u0%20p0%20c0%20%7B2,B%7D%20%7B6,B%7D%20%7B9,S%7D;6%20C%20u0%20p0%20c0%20%7B4,B%7D%20%7B5,B%7D%20%7B10,S%7D;7%20C%20u1%20p0%20c0%20%7B1,S%7D%20%7B13,D%7D;8%20O%20u0%20p2%20c0%20%7B2,S%7D%20%7B14,S%7D;9%20H%20u0%20p0%20c0%20%7B5,S%7D;10%20H%20u0%20p0%20c0%20%7B6,S%7D;11%20H%20u0%20p0%20c0%20%7B4,S%7D;12%20H%20u0%20p0%20c0%20%7B3,S%7D;13%20O%20u0%20p2%20c0%20%7B7,D%7D;14%20H%20u0%20p0%20c0%20%7B8,S%7D;) you get an error, which I'll open a separate issue for.)

**Comment by jonwzheng** [comment]
This has been fixed.
