### ISSUE TITLE
Assertion Error in Reaction Search

### ISSUE THREAD

**Issue by whgreen** [ReactionMechanismGenerator/RMG-website#80]
http://rmg.mit.edu/database/kinetics/families/R_Recombination/rate_rules/reactant1=multiplicity%202;1%20C%20u0%20p0%20c0%20{2,S}%20{3,D}%20{7,S};2%20C%20u0%20p0%20c0%20{1,S}%20{4,D}%20{8,S};3%20C%20u0%20p0%20c0%20{1,D}%20{6,S}%20{10,S};4%20C%20u0%20p0%20c0%20{2,D}%20{5,S}%20{9,S};5%20C%20u0%20p0%20c0%20{4,S}%20{6,D}%20{11,S};6%20C%20u0%20p0%20c0%20{3,S}%20{5,D}%20{12,S};7%20C%20u1%20p0%20c0%20{1,S}%20{13,S}%20{14,S};8%20H%20u0%20p0%20c0%20{2,S};9%20H%20u0%20p0%20c0%20{4,S};10%20H%20u0%20p0%20c0%20{3,S};11%20H%20u0%20p0%20c0%20{5,S};12%20H%20u0%20p0%20c0%20{6,S};13%20H%20u0%20p0%20c0%20{7,S};14%20H%20u0%20p0%20c0%20{7,S};__reactant2=multiplicity%202;1%20C%20u0%20p0%20c0%20{2,S}%20{4,S}%20{14,D};2%20C%20u0%20p0%20c0%20{1,S}%20{7,S}%20{12,D};3%20C%20u1%20p0%20c0%20{9,S}%20{10,S}%20{11,S};4%20H%20u0%20p0%20c0%20{1,S};5%20H%20u0%20p0%20c0%20{12,S};6%20H%20u0%20p0%20c0%20{13,S};7%20H%20u0%20p0%20c0%20{2,S};8%20H%20u0%20p0%20c0%20{14,S};9%20H%20u0%20p0%20c0%20{3,S};10%20H%20u0%20p0%20c0%20{3,S};11%20C%20u0%20p0%20c0%20{3,S}%20{12,S}%20{13,D};12%20C%20u0%20p0%20c0%20{2,D}%20{5,S}%20{11,S};13%20C%20u0%20p0%20c0%20{6,S}%20{11,D}%20{14,S};14%20C%20u0%20p0%20c0%20{1,D}%20{8,S}%20{13,S};__product1=1%20C%20u0%20p0%20c0%20{2,S}%20{3,S}%20{15,S}%20{16,S};2%20C%20u0%20p0%20c0%20{1,S}%20{4,S}%20{17,S}%20{18,S};3%20C%20u0%20p0%20c0%20{1,S}%20{5,B}%20{6,B};4%20C%20u0%20p0%20c0%20{2,S}%20{7,B}%20{8,B};5%20C%20u0%20p0%20c0%20{3,B}%20{9,B}%20{19,S};6%20C%20u0%20p0%20c0%20{3,B}%20{11,B}%20{21,S};7%20C%20u0%20p0%20c0%20{4,B}%20{13,B}%20{25,S};8%20C%20u0%20p0%20c0%20{4,B}%20{14,B}%20{26,S};9%20C%20u0%20p0%20c0%20{5,B}%20{10,B}%20{20,S};10%20C%20u0%20p0%20c0%20{9,B}%20{11,B}%20{22,S};11%20C%20u0%20p0%20c0%20{6,B}%20{10,B}%20{23,S};12%20C%20u0%20p0%20c0%20{13,B}%20{14,B}%20{24,S};13%20C%20u0%20p0%20c0%20{7,B}%20{12,B}%20{27,S};14%20C%20u0%20p0%20c0%20{8,B}%20{12,B}%20{28,S};15%20H%20u0%20p0%20c0%20{1,S};16%20H%20u0%20p0%20c0%20{1,S};17%20H%20u0%20p0%20c0%20{2,S};18%20H%20u0%20p0%20c0%20{2,S};19%20H%20u0%20p0%20c0%20{5,S};20%20H%20u0%20p0%20c0%20{9,S};21%20H%20u0%20p0%20c0%20{6,S};22%20H%20u0%20p0%20c0%20{10,S};23%20H%20u0%20p0%20c0%20{11,S};24%20H%20u0%20p0%20c0%20{12,S};25%20H%20u0%20p0%20c0%20{7,S};26%20H%20u0%20p0%20c0%20{8,S};27%20H%20u0%20p0%20c0%20{13,S};28%20H%20u0%20p0%20c0%20{14,S};

**Comment by rwest** [comment]
Since the URL syntax was changed we can no longer debug this issue, if it still exists. So I'll assume it has been resolved. See discussion in https://github.com/ReactionMechanismGenerator/RMG-Py/issues/668
