### ISSUE TITLE
Errors in Generate Flux Diagram

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-website#82]
The flux diagram feature throws an error:

Environment:

Request Method: POST
Request URL: http://rmg.mit.edu/simulate/flux.  Here is the error message

Django Version: 1.3.1
Python Version: 2.7.6
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.markup',
 'django.contrib.admin',
 'main',
 'main.templatetags',
 'database',
 'pdep',
 'rmg']
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  111.                         response = callback(request, *callback_args, **callback_kwargs)
File "/var/www/RMG-website/rmgweb/rmg/views.py" in generateFlux
  199.             createFluxDiagram(flux.path, input, chemkin, dict, java, settings, chemkinOutput)
File "/var/www/RMG-Py/generateFluxDiagram.py" in createFluxDiagram
  596.                                 centralSpecies, speciesPath, settings)
File "/var/www/RMG-Py/generateFluxDiagram.py" in generateFluxDiagram
  241.             graph.write_dot(os.path.join(outputDirectory, 'flux_diagram_{0:04d}.dot'.format(frameNumber)))
File "/usr/lib/python2.7/dist-packages/pydot.py" in <lambda>
  1809.                 lambda path, f=frmt, prog=self.prog : self.write(path, format=f, prog=prog))
File "/usr/lib/python2.7/dist-packages/pydot.py" in write
  1895.         dot_fd = file(path, "w+b")

Exception Type: IOError at /simulate/flux
Exception Value: [Errno 2] No such file or directory: '/var/www/RMG-website/rmgweb/media/rmg/tools/flux/1/flux_diagram_0053.dot'

**Comment by alongd** [comment]
I got a different error message:

```
NameError at /simulate/flux

global name 'dot_parser' is not defined

Request Method: 	POST
Request URL: 	http://rmg.mit.edu/simulate/flux
Django Version: 	1.9.5
Exception Type: 	NameError
Exception Value: 	

global name 'dot_parser' is not defined

Exception Location: 	build/bdist.linux-x86_64/egg/pydot.py in graph_from_dot_data, line 220
Python Executable: 	/usr/bin/python
Python Version: 	2.7.6
Python Path: 	

['/var/www/RMG-website/rmgweb',
 '/var/www/RMG-Py',
 '/opt/anaconda/envs/rmg_env/lib/python2.7/site-packages/gprof2dot-2015.2.3-py2.7.egg',
 '/opt/anaconda/envs/rmg_env/lib/python2.7/site-packages/pydot2-1.0.32-py2.7.egg',
 '/opt/anaconda/envs/rmg_env/lib/python2.7/site-packages/scoop-0.7.2.0-py2.7.egg',
 '/opt/anaconda/envs/rmg_env/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg',
 '/opt/anaconda/envs/rmg_env/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/dist-packages/PyDAS-1.0.0-py2.7-linux-x86_64.egg',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client',
 '/var/www/RMG-website',
 '/var/www/RMG-website/rmgweb',
 '/var/www/RMG-database',
 '/var/www/RMG-Py']


Environment:


Request Method: POST
Request URL: http://rmg.mit.edu/simulate/flux

Django Version: 1.9.5
Python Version: 2.7.6
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.admin',
 'rmgweb.main',
 'rmgweb.main.templatetags',
 'rmgweb.database',
 'rmgweb.pdep',
 'rmgweb.rmg')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')



Traceback:

File "/opt/anaconda/envs/rmg_env/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/opt/anaconda/envs/rmg_env/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/www/RMG-website/rmgweb/rmg/views.py" in generateFlux
  199.             createFluxDiagram(flux.path, input, chemkin, dict, java, settings, chemkinOutput)

File "/var/www/RMG-Py/rmgpy/tools/fluxdiagram.py" in createFluxDiagram
  490.                                 centralSpecies, speciesPath, settings)

File "/var/www/RMG-Py/rmgpy/tools/fluxdiagram.py" in generateFluxDiagram
  196.     graph = pydot.graph_from_dot_data(graph.create_dot(prog=program))

File "build/bdist.linux-x86_64/egg/pydot.py" in graph_from_dot_data
  220.     return dot_parser.parse_dot_data(data)

Exception Type: NameError at /simulate/flux
Exception Value: global name 'dot_parser' is not defined

```

**Comment by mliu49** [comment]
This error can be fixed by downgrading `pyparsing` to version 2.0.3. I'm not sure what change in `pyparsing` broke this though. This also affects running `generateFluxDiagram.py` directly from the command line.

@connie, should we add a version specification to `environment.yml`? Also, installing `pydot` from the RMG anaconda channel forces `pyparsing` to be upgraded to version 2.1.4. Is it possible for that to be changed?

**Comment by rwest** [comment]
Not a very satisfactory fix. Could you look a bit more into it see if upgrading pydot instead of downgrading pyparsing can do it? Eg http://stackoverflow.com/questions/15951748/pydot-and-graphviz-error-couldnt-import-dot-parser-loading-of-dot-files-will

**Comment by mliu49** [comment]
Our version of pydot supposedly fixed that issue already. The update from pyparsing 1.5.7 to 2.x caused the issue the first time, which the update from pydot 1.0.28 to the current pydot 2.0.1 on the RMG channel fixed. For some reason pyparsing 2.0.3 --> 2.1.4 broke this again. Perhaps the current [master](https://github.com/erocarrera/pydot) for pydot fixes it again, but I need to learn how to test that, since there's no anaconda package.

**Comment by mliu49** [comment]
Ok, I tested [pydot 1.2.2](https://pypi.python.org/pypi/pydot) and it works with pyparsing 2.1.4, following a minor change in `fluxDiagram.py`. I'll make a pull request for this change and some fixes I'm still working for other errors, and I can work with Connie to change our conda package for pydot.
