### ISSUE TITLE
RuntimeError when loading kinetics database

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-website#91]
After some testing, I found that commit ReactionMechanismGenerator/RMG-Py@199a993 is the one that breaks the website.

The error seems to occur when loading any page which needs the kinetics database, such as /database/kinetics/ or /database/kinetics/search/.

The traceback is as follows:

    Environment:
    
    
    Request Method: GET
    Request URL: http://127.0.0.1:8000/database/kinetics/
    
    Django Version: 1.3.7
    Python Version: 2.7.10
    Installed Applications:
    ['django.contrib.auth',
     'django.contrib.contenttypes',
     'django.contrib.sessions',
     'django.contrib.sites',
     'django.contrib.messages',
     'django.contrib.markup',
     'django.contrib.admin',
     'main',
     'main.templatetags',
     'database',
     'pdep',
     'rmg']
    Installed Middleware:
    ('django.middleware.common.CommonMiddleware',
     'django.contrib.sessions.middleware.SessionMiddleware',
     'django.middleware.csrf.CsrfViewMiddleware',
     'django.contrib.auth.middleware.AuthenticationMiddleware',
     'django.contrib.messages.middleware.MessageMiddleware')
    
    
    Traceback:
    File "/home/mjliu/anaconda/envs/rmg/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
      111.                         response = callback(request, *callback_args, **callback_kwargs)
    File "/home/mjliu/Code/RMG-website/rmgweb/database/views.py" in kinetics
      1197.     rmgDatabase = loadDatabase('kinetics', section)
    File "/home/mjliu/Code/RMG-website/rmgweb/database/tools.py" in loadDatabase
      202.                 database.kinetics.loadFamilies(dirpath, families = 'all', depositories = 'all')
    File "/home/mjliu/Code/RMG-Py/rmgpy/data/kinetics/database.py" in loadFamilies
      190.             family.load(familyPath, self.local_context, self.global_context, depositoryLabels=depositories)
    File "/home/mjliu/Code/RMG-Py/rmgpy/data/kinetics/family.py" in load
      577.                     depository.load(fpath, local_context, global_context)
    File "/home/mjliu/Code/RMG-Py/rmgpy/data/kinetics/depository.py" in load
      127.         speciesDict = self.getSpecies(os.path.join(os.path.dirname(path),'dictionary.txt'))
    File "/home/mjliu/Code/RMG-Py/rmgpy/data/base.py" in getSpecies
      284.                     species.generateResonanceIsomers()
    
    Exception Type: RuntimeError at /database/kinetics/
    Exception Value: Range Error

Additionally, this error appears in the terminal:

    ****
    Range Error
    idx2
    Violation occurred on line 289 in file /home/rdkit/miniconda/conda-bld/work/Code/GraphMol/ROMol.cpp
    Failed Expression: 0 <= 9 <= 8
    ****

Each time, the species that it's trying to generate resonance isomers for is

    Species(label="C9H9", molecule=[Molecule(SMILES="[CH]1CC1c1ccccc1")])

Hopefully this information is helpful to someone who understands this better than I do. I don't know where I would even start trying to fix the problem.

**Comment by nickvandewiele** [comment]
So, I created the following unittest for the aforementioned C9H9, 
```python
import unittest

from rmgpy.species import Species
from rmgpy.molecule.molecule import Molecule

class ResonanceTest(unittest.TestCase):

    def test_C9H9(self):
        spc = Species(label="C9H9", molecule=[Molecule(SMILES="[CH]1CC1c1ccccc1")])
        spc.generateResonanceIsomers()



```

and got this error:
```python
****
Range Error
idx2
Violation occurred on line 288 in file /home/vagrant/venv/rdkit/Code/GraphMol/ROMol.cpp
Failed Expression: 0 <= 9 <= 8
****

ERROR

======================================================================
ERROR: test_C9H9 (resonanceTest.ResonanceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant_data/model_reduction/ws/RMG-Py/resonanceTest.py", line 10, in test_C9H9
    spc.generateResonanceIsomers()
  File "rmgpy/species.py", line 184, in rmgpy.species.Species.generateResonanceIsomers (build/pyrex/rmgpy/species.c:4581)
    def generateResonanceIsomers(self):
  File "rmgpy/species.py", line 192, in rmgpy.species.Species.generateResonanceIsomers (build/pyrex/rmgpy/species.c:4520)
    self.molecule = self.molecule[0].generateResonanceIsomers()
  File "rmgpy/molecule/molecule.py", line 1471, in rmgpy.molecule.molecule.Molecule.generateResonanceIsomers (build/pyrex/rmgpy/molecule/molecule.c:27959)
    def generateResonanceIsomers(self):
  File "rmgpy/molecule/molecule.py", line 1499, in rmgpy.molecule.molecule.Molecule.generateResonanceIsomers (build/pyrex/rmgpy/molecule/molecule.c:27698)
    newIsomers = isomer.getAromaticResonanceIsomers()
  File "rmgpy/molecule/molecule.py", line 1711, in rmgpy.molecule.molecule.Molecule.getAromaticResonanceIsomers (build/pyrex/rmgpy/molecule/molecule.c:30398)
    if str(rdkitmol.GetBondBetweenAtoms(rdAtomIndices[atom1],rdAtomIndices[atom2]).GetBondType()) == 'AROMATIC':
RuntimeError: Range Error

```

**Comment by nickvandewiele** [comment]
The unittests in

https://github.com/ReactionMechanismGenerator/RMG-Py/commit/68b78a8b701a22dcaec6006c305f90bb5d49c3ac

show that the error occurs specifically for cyclopropylbenzene regardless of the nature of the benzene bonds (aromatic vs kekulized), regardless of whether there is an unpaired electron in the cyclopropyl ring.

The test also shows that the error does not occur for cyclobutylbenzene, nor for propylbenzene.

**Comment by nickvandewiele** [comment]
https://github.com/ReactionMechanismGenerator/RMG-Py/commit/55a0340cc1c8dcbf9a75777e543a8a5194179399

ensures that H's are not removed from the rdkit molecule. After doing so, the errors disappear.

Here is my explanation, why this works.

The reason why this crashed after my atom sorting modifications is because
`mol.sortAtoms()` is called in `parser.toRDKitMol(...)`. The new atom sorting algorithm leads to an atom order in which the non-hydrogen atoms do not necessarily have atom indices within the range (0 - no. of heavy atoms).

When the following line is executed:
```python
rdkitmol.GetBondBetweenAtoms(rdAtomIndices[atom1],rdAtomIndices[atom2])
```

`rdAtomIndices[atom1]` returns an index, e.g. 9 that is higher than the number of atoms in the created rdkitmol, which leads to the crash.

**Comment by nickvandewiele** [comment]
Why did this not lead to crashes in `make egx`? Probably because we don't have examples in which aromatics are created.

**Comment by rwest** [comment]
I'm nervous your 'fix' of not removing the H atoms just hides an issue. 
The problem only shows up and crashes when you ask RDKit for the 9th atom when it only has 8 atoms, but this probably means that we've been asking for the wrong indices in other situations, eg. asking forth 8th atom when we meant the 7th, even if there were 9 and so it didn't crash. 
Can you check that rdAtomIndices really does contain the RDKit atom indices? (then you should be able to remove the H atoms if you wish?).

**Comment by rwest** [comment]
Also, there may be something to be said for a sorting algorithm that *does* always put the Hs at the end. Means you don't have to renumber everything if you remove them. I can't remember if this was a design decision with the previous sorting algorithm - it might have been.

**Comment by nickvandewiele** [comment]
I guess, ensuring that heavy atoms come first, could be accomplished by reversing the order of the sorting attributes:

```python
def getDescriptor(self):
        return (self.getAtomConnectivityValue(), self.symbol, self.radicalElectrons, self.lonePairs, self.charge)

```

to 
```python
def getDescriptor(self):
        return (self.symbol.number, self.getAtomConnectivityValue(), self.radicalElectrons, self.lonePairs, self.charge)
```

since this method is called in 
```python
    def sortAtoms(self):
...
        self.atoms.sort(key=lambda a: a.getDescriptor())
...
```

**Comment by nickvandewiele** [comment]
I believe the method `toRDKitMol(molecule, removeHs=..., returnMapping=...)` with one particular combination of `removeHs` and `returnMapping`.

As a reminder:
`removeHs`: removes the hydrogen atoms from the generated RDKit Mol. 

This is handy when we pass the RDKit Mol to the SMILES generator. Removing the H's ensure that SMILES do not explicitly report H's in the string. Methane will be converted to `C`, rather than the less legible `[H]C([H])([H])[H]`.

`returnMapping`: a dictionary with RMGAtom objects as keys and the corresponding index in the generated RDKitMol.

The problem arises when we call `.toRDKitMol(molecule, removeHs=True, returnMapping=True)`
In this situation we remove the H's atoms in the rdkitmol, but we still iterate over the H atoms in the original RMG Molecule:

```python
    rdAtomIndices = {} # dictionary of RDKit atom indices
    rdkitmol = Chem.rdchem.EditableMol(Chem.rdchem.Mol())
    for index, atom in enumerate(mol.vertices):
        rdAtom = Chem.rdchem.Atom(atom.element.symbol)
        ...
        rdAtomIndices[atom] = index
```

So, we point the RMG-H-Atom object to an index that we want to lookup in the rdkitmol, that will not exist if we have removed the H atoms in the rdkit mol.

The reason why this never crashed, is because we never lookup H atoms in the RMG Molecule. The only call that has the risky combo of parameter (`getAromaticResonanceIsomers`), only looks up carbon atoms.

**Comment by nickvandewiele** [comment]
https://github.com/ReactionMechanismGenerator/RMG-Py/commit/667554294e77d94f8f4656824f22633f5f46b04a prevents adding H atoms to rdAtomIndices when `removeHs=True`.
