### ISSUE TITLE
ImportError for Generate Flux Diagram

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-website#93]
As a side effect of moving the standalone scripts in RMG-Py to the /scripts/ folder, some of the website functionality was broken. Some issues were fixed by just changing the path, but diffModels and generateFluxDiagrams relied on importing their respective modules.

Commit @5ef2800 was intended to fix this issue by adding the /scripts/ folder to the search path, but it was reverted in favor of calling diffModels directly. However, generateFluxDiagrams is now back to being broken.

I'm creating this issue to make sure it doesn't get forgotten, since I don't think it gets used very often.

**Comment by rwest** [comment]
It does get used sometimes, alas. @PWstmrlnd just tried to demonstrate it to the Nancy group, and got this error. A fix would be great...

**Comment by nickvandewiele** [comment]
After some discussion, we came up with the following design:

We would create a `tools` package within the RMG-Py project that contains a `fluxdiagram` module. This module contains the main functionality of the flux diagram script in the scripts folder. The file in the scripts folder as well as the website would point to the functions within the tools package.
