### ISSUE TITLE
Repo not compatible with most recent version of Django

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-website#94]
`execute_manager` is deprecated in versions django 1.4+ and removed in 1.6+. Current version is 1.8.5.

https://github.com/ReactionMechanismGenerator/RMG-website/blob/master/rmgweb/manage.py#L31

http://stackoverflow.com/questions/20906305/import-error-cannot-import-name-execute-manager-in-windows-environment

**Comment by rwest** [comment]
@nick-rc I suggest you watch (and/or contribute to) this issue (and @nickvandewiele please keep it updated if/as you work on fixing)

**Comment by nickvandewiele** [comment]
See https://github.com/ReactionMechanismGenerator/RMG-website/tree/django_185

**Comment by nick-rc** [comment]
@rwest I'll be working on upgrading the site today so I can see if this issue can be resolved while I do that. I'll update with any info I get

**Comment by nickvandewiele** [comment]
Should be solved by #96
